/**
 * Curated and crawled list of MT5 broker servers (1,300+ servers).
 * Crawled from live broker platform directory + enriched with top retail brokers & prop firms.
 * Traders can also enter custom server names if their broker is not in this list.
 */

export interface MT5ServerItem {
    name: string;
    broker?: string;
    isDemo?: boolean;
}

export const POPULAR_MT5_SERVERS: MT5ServerItem[] = [
    { name: "1xTrade-Server", broker: "1xTrade" },
    { name: "4xCube-MT5", broker: "4xCube" },
    { name: "4xHubInternational-Server", broker: "4xHub" },
    { name: "AAAFx-5 Demo", broker: "AAAFx", isDemo: true },
    { name: "ACCapital-Demo", broker: "AC Capital", isDemo: true },
    { name: "ACCapital-Live", broker: "AC Capital" },
    { name: "ACCapitalMarket-Demo", broker: "AC Capital", isDemo: true },
    { name: "ACCapitalMarket-Real", broker: "AC Capital" },
    { name: "ACCMGlobal-Demo", broker: "ACCMGlobal", isDemo: true },
    { name: "ACCMintl-Real", broker: "ACCMintl" },
    { name: "AccuindexLimited-Live", broker: "Accuindex" },
    { name: "Accumarkets-Live", broker: "Accumarkets" },
    { name: "Acetop-Demo", broker: "Acetop", isDemo: true },
    { name: "AcetopFinancial-MetalsDataFeeds", broker: "Acetop" },
    { name: "ACGMarkets-Main", broker: "ACGMarkets" },
    { name: "AchieverGlobalMarkets-Server", broker: "AchieverGlobalMarkets" },
    { name: "ACMGlobal-Demo", broker: "ACMGlobal", isDemo: true },
    { name: "ActivTrades-Server", broker: "ActivTrades" },
    { name: "ActivTradesCorp-Server", broker: "ActivTrades" },
    { name: "ActivTradesEU-Server", broker: "ActivTrades" },
    { name: "ActivTradesInt-Server", broker: "ActivTrades" },
    { name: "ActivTradesMarkets-Server", broker: "ActivTrades" },
    { name: "ACYSecurities-Live", broker: "ACYSecurities" },
    { name: "ADFXGlobal-Live", broker: "ADFXGlobal" },
    { name: "AdmiralsGroup-Demo", broker: "Admirals", isDemo: true },
    { name: "AdmiralsGroup-Live", broker: "Admirals" },
    { name: "AdmiralsSC-Demo", broker: "Admirals", isDemo: true },
    { name: "AdmiralsSC-Live", broker: "Admirals" },
    { name: "AdvancedMarkets-Demo", broker: "AdvancedMarkets", isDemo: true },
    { name: "AdvancedMarketsLLC-EDU", broker: "AdvancedMarketsLLC", isDemo: true },
    { name: "AdvancedMarketsLLC-Live", broker: "AdvancedMarketsLLC" },
    { name: "AdvancedMarketsUK-Demo", broker: "AdvancedMarketsUK", isDemo: true },
    { name: "AeronLimited-Server", broker: "AeronLimited" },
    { name: "AETOSMarkets-Live MT5", broker: "AETOSMarkets" },
    { name: "AETOSMarketsM-Live MT5", broker: "AETOSMarketsM" },
    { name: "AetramTrades-Demo", broker: "AetramTrades", isDemo: true },
    { name: "Afterprime-Ltd", broker: "Afterprime" },
    { name: "AgileGlobal-Live", broker: "AgileGlobal" },
    { name: "AIFOGlobal-Live", broker: "AIFOGlobal" },
    { name: "Aiprime-Server", broker: "Aiprime" },
    { name: "AirrsanFX-Live", broker: "AirrsanFX" },
    { name: "AlchemyMarkets-Server", broker: "AlchemyMarkets" },
    { name: "AlfaForexRU-Real", broker: "AlfaForexRU" },
    { name: "ALFX-Trade", broker: "ALFX" },
    { name: "AlignMarkets-Trade", broker: "IG" },
    { name: "Alpari-MT5", broker: "Alpari" },
    { name: "Alpari-MT5-Demo", broker: "Alpari", isDemo: true },
    { name: "AlphaGlobalMarket-Live", broker: "AlphaGlobalMarket" },
    { name: "AlSamaaGoldLLC-Demo", broker: "AlSamaaGoldLLC", isDemo: true },
    { name: "Altum-MT5-1", broker: "Altum" },
    { name: "AmanaCapital-Live", broker: "AmanaCapital" },
    { name: "AMarkets-Demo", broker: "AMarkets", isDemo: true },
    { name: "AMarkets-Real", broker: "AMarkets" },
    { name: "AMPGlobalEU-Live", broker: "AMPGlobalEU" },
    { name: "AMPGlobalUSA-Live", broker: "AMPGlobalUSA" },
    { name: "AnaxCapitalFinancial-Trade", broker: "AnaxCapitalFinancial" },
    { name: "Anaxcapitalmarkets-Server", broker: "Anaxcapitalmarkets" },
    { name: "Anzocapital-live", broker: "Anzocapital" },
    { name: "ApexCapitalMarkets-ECN", broker: "ApexCapitalMarkets" },
    { name: "AprilInvestors-Server", broker: "AprilInvestors" },
    { name: "AquaFunded-Server", broker: "AquaFunded" },
    { name: "ArazFX-MetaTrader5", broker: "ArazFX" },
    { name: "AronMarkets-Demo", broker: "AronMarkets", isDemo: true },
    { name: "AronMarkets-MT5", broker: "AronMarkets" },
    { name: "ascendsglobalmarkets-Server", broker: "ascendsglobalmarkets" },
    { name: "AsiaProBerjangka2-REAL", broker: "AsiaProBerjangka2" },
    { name: "AssexmarketsGlobal-Trade", broker: "XM" },
    { name: "ATCBrokers-MT5", broker: "ATCBrokers" },
    { name: "ATFXGM10-Live", broker: "ATFXGM10" },
    { name: "ATFXGM13-ATF-DEMO", broker: "ATFXGM13", isDemo: true },
    { name: "ATFXGM13-Demo", broker: "ATFXGM13", isDemo: true },
    { name: "ATFXGM16-LIVE", broker: "ATFXGM16" },
    { name: "ATFXGM18-ATF-DEMO", broker: "ATFXGM18", isDemo: true },
    { name: "ATFXGM18-Demo", broker: "ATFXGM18", isDemo: true },
    { name: "ATFXGM18-Live", broker: "ATFXGM18" },
    { name: "ATFXGM19-Live", broker: "ATFXGM19" },
    { name: "ATFXGM21-ATF-DEMO", broker: "ATFXGM21", isDemo: true },
    { name: "ATFXGM21-Demo", broker: "ATFXGM21", isDemo: true },
    { name: "ATFXGM23-ATF-LIVE", broker: "ATFXGM23" },
    { name: "ATFXGM23-Live", broker: "ATFXGM23" },
    { name: "ATFXGM25-LIVE", broker: "ATFXGM25" },
    { name: "ATFXGM5-DEMO", broker: "ATFXGM5", isDemo: true },
    { name: "ATFXGM6-Live", broker: "ATFXGM6" },
    { name: "ATFXKH-LIVE2", broker: "ATFXKH" },
    { name: "AtlasFunded-Server", broker: "AtlasFunded" },
    { name: "ATMCapital-Server", broker: "ATMCapital" },
    { name: "AtmosGlobal-LIVE", broker: "AtmosGlobal" },
    { name: "AudaCityGlobal-Live", broker: "AudaCityGlobal" },
    { name: "AuricInternationalMarkets-Live", broker: "AuricInternationalMarkets" },
    { name: "AuroMarkets-Server", broker: "AuroMarkets" },
    { name: "AutoFX-MT5", broker: "AutoFX" },
    { name: "Ava-Demo 1-MT5", broker: "Ava", isDemo: true },
    { name: "Ava-Real 1-MT5", broker: "Ava" },
    { name: "AvaTradeMarkets-Demo 1-MT5", broker: "AvaTrade", isDemo: true },
    { name: "AvaTradeMarkets-Real 1-MT5", broker: "AvaTrade" },
    { name: "Axi-UK55-Live", broker: "Axi" },
    { name: "Axi-US50-Demo", broker: "Axi", isDemo: true },
    { name: "Axi-US50-Live", broker: "Axi" },
    { name: "Axi-US51-Live", broker: "Axi" },
    { name: "Axi-US52-Live", broker: "Axi" },
    { name: "AXI-US54-Live", broker: "Axi" },
    { name: "AxiaPhoenixFine-MT5", broker: "Axi" },
    { name: "AxionTrade-Live", broker: "Axi" },
    { name: "AxionTradeKH-Demo", broker: "Axi", isDemo: true },
    { name: "Axiory-Demo", broker: "Axi", isDemo: true },
    { name: "AXPM-Server", broker: "AXPM" },
    { name: "AYAMarkets-Server", broker: "AYAMarkets" },
    { name: "Baazex-Live", broker: "Baazex" },
    { name: "BarclayStone-Live", broker: "BarclayStone" },
    { name: "BaxiaMarkets-UK01", broker: "Axi" },
    { name: "BCMMarkets-Server", broker: "BCMMarkets" },
    { name: "BCR-MT5", broker: "BCR" },
    { name: "BeirmanCapital-Server", broker: "BeirmanCapital" },
    { name: "BenchMark-Server", broker: "BenchMark" },
    { name: "BePrimeGroup-Server", broker: "BePrimeGroup" },
    { name: "BestonFX-Server", broker: "BestonFX" },
    { name: "BestonInternetTech-Server", broker: "BestonInternetTech" },
    { name: "BeyondIQCapital-Server", broker: "BeyondIQCapital" },
    { name: "BICMarkets-Server", broker: "IC Markets" },
    { name: "BigBossHoldings-LIVE2", broker: "IG" },
    { name: "BigBossLtd-LIVE2", broker: "IG" },
    { name: "BigBossMuLtd-LIVE1", broker: "IG" },
    { name: "BigGlobalMarkets-Trade", broker: "IG" },
    { name: "BigLot-Server", broker: "IG" },
    { name: "BigMoCapital-Server", broker: "IG" },
    { name: "BIGMOCapitalLtd-Server", broker: "IG" },
    { name: "BigrayFinanceGroup-Server", broker: "IG" },
    { name: "BIGSolutions-LIVE1", broker: "IG" },
    { name: "Bitdelta-Limited", broker: "Bitdelta" },
    { name: "Bitget-MT5-LIVE2", broker: "Bitget" },
    { name: "BizzTrade-Server", broker: "BizzTrade" },
    { name: "BlackBullMarkets-Demo", broker: "BlackBull", isDemo: true },
    { name: "BlackBullMarkets-Live", broker: "BlackBull" },
    { name: "BlueberryMarkets-Demo", broker: "BlueberryMarkets", isDemo: true },
    { name: "BlueberryMarkets-Demo02", broker: "BlueberryMarkets", isDemo: true },
    { name: "BlueberryMarkets-Live", broker: "BlueberryMarkets" },
    { name: "BlueberryMarkets-Live02", broker: "BlueberryMarkets" },
    { name: "BlueberryMarketsSVG-Live", broker: "BlueberryMarketsSVG" },
    { name: "BlueberryMarketsV-Live3", broker: "BlueberryMarketsV" },
    { name: "BlueChipBroker-Server", broker: "BlueChipBroker" },
    { name: "BlueGuardian-Server", broker: "BlueGuardian" },
    { name: "BlueSuisse-Demo", broker: "BlueSuisse", isDemo: true },
    { name: "BlueSuisse-Global", broker: "BlueSuisse" },
    { name: "BlueWhaleMarkets-Server", broker: "BlueWhaleMarkets" },
    { name: "BOSSAFX-Real", broker: "BOSSAFX" },
    { name: "Bostonmex-Demo", broker: "Bostonmex", isDemo: true },
    { name: "BrainstormMarkets-Server", broker: "BrainstormMarkets" },
    { name: "BreakthroughCapital-Server", broker: "BreakthroughCapital" },
    { name: "Bridgemarkets-MT5", broker: "Bridgemarkets" },
    { name: "BrightenMarkets-Live", broker: "IG" },
    { name: "BrightFunded-Server", broker: "IG" },
    { name: "BrightHouseCapitalMarkets-Training", broker: "IG" },
    { name: "BrightWin-Markets", broker: "IG" },
    { name: "BristolHouse-Live", broker: "BristolHouse" },
    { name: "BroctagonPrimeMarkets-Live", broker: "BroctagonPrimeMarkets" },
    { name: "BrokStockSA-Real", broker: "BrokStockSA" },
    { name: "BTGTMauritiusCapital-MT5-LIVE1", broker: "BTGTMauritiusCapital" },
    { name: "BTGTMauritiusCapital-MT5-LIVE2", broker: "BTGTMauritiusCapital" },
    { name: "BulgeGroup-Real", broker: "BulgeGroup" },
    { name: "Bullfy-Trade", broker: "Bullfy" },
    { name: "BullsouqGlobalLimited-Server", broker: "BullsouqGlobalLimited" },
    { name: "BullWaves-LIVE", broker: "BullWaves" },
    { name: "Bybit-Demo", broker: "Bybit", isDemo: true },
    { name: "Bybit-Live", broker: "Bybit" },
    { name: "Bybit-live-2", broker: "Bybit" },
    { name: "Bybit-live-4", broker: "Bybit" },
    { name: "Bybit-live-5", broker: "Bybit" },
    { name: "Bybit-live-6", broker: "Bybit" },
    { name: "Bybit-Live-7", broker: "Bybit" },
    { name: "BybitX-Live", broker: "BybitX" },
    { name: "BytroxGlobal-Server", broker: "BytroxGlobal" },
    { name: "Capital.com-Live", broker: "Capital.com" },
    { name: "Capital.ComAU-Live", broker: "Capital.ComAU" },
    { name: "Capital.ComBah-Live", broker: "Capital.ComBah" },
    { name: "Capital.ComMena-Live", broker: "Capital.ComMena" },
    { name: "Capital.ComUK-Live", broker: "Capital.ComUK" },
    { name: "CapitalChain-Trade", broker: "CapitalChain" },
    { name: "CapitalPointTrading-Demo", broker: "CapitalPointTrading", isDemo: true },
    { name: "CapitalPointTrading-MT5-4", broker: "CapitalPointTrading" },
    { name: "CapitalxtendLLC-MU", broker: "CapitalxtendLLC" },
    { name: "Capstock-Server", broker: "Capstock" },
    { name: "CaravelleInvestments-MT5", broker: "CaravelleInvestments" },
    { name: "CarltonFinancial-Server", broker: "CarltonFinancial" },
    { name: "CDJSocialStocks-Server", broker: "CDJSocialStocks" },
    { name: "CelestialTrader-Real", broker: "CelestialTrader" },
    { name: "CFI1-Real", broker: "CFI1" },
    { name: "CFI11-Real", broker: "CFI11" },
    { name: "CFI13-Real2", broker: "CFI13" },
    { name: "CFI15-Real2", broker: "CFI15" },
    { name: "CFI2-Real", broker: "CFI2" },
    { name: "CFI3-Demo", broker: "CFI3", isDemo: true },
    { name: "CFI3-Real", broker: "CFI3" },
    { name: "CGInvest-Server", broker: "CGInvest" },
    { name: "Charleston-Live1", broker: "Charleston" },
    { name: "CityTradersImperium-Real", broker: "CityTradersImperium" },
    { name: "ClassicGlobal-Server", broker: "ClassicGlobal" },
    { name: "ClearInvestimentos-DEMO", broker: "ClearInvestimentos", isDemo: true },
    { name: "CMCMarkets-MT5-LIVE", broker: "CMCMarkets" },
    { name: "CMSFinancial-Server", broker: "CMSFinancial" },
    { name: "Coinexx-Demo", broker: "Coinexx", isDemo: true },
    { name: "Coinexx-Live", broker: "Coinexx" },
    { name: "CombatCapitalMarkets-Server", broker: "CombatCapitalMarkets" },
    { name: "ComoForeignExchange-Server", broker: "IG" },
    { name: "Connext-Demo", broker: "Connext", isDemo: true },
    { name: "Connext-Real", broker: "Connext" },
    { name: "CoxigoMarkets-Server", broker: "IG" },
    { name: "CPTMarkets-Live", broker: "CPTMarkets" },
    { name: "CribMarket-Live", broker: "CribMarket" },
    { name: "CronosMarkets-Trade", broker: "CronosMarkets" },
    { name: "CrownstoneFinancial-Server", broker: "CrownstoneFinancial" },
    { name: "CTSCloudTrading-Live", broker: "CTSCloudTrading" },
    { name: "CuboMarkets-Server", broker: "CuboMarkets" },
    { name: "CWGMarketsSVG-Live", broker: "CWGMarketsSVG" },
    { name: "CWGMarketsUK-Live", broker: "CWGMarketsUK" },
    { name: "CXM-Primary", broker: "XM" },
    { name: "CXMDirect-Demo", broker: "XM", isDemo: true },
    { name: "CXMDirect-Live", broker: "XM" },
    { name: "CXMTrading-Primary", broker: "XM" },
    { name: "DamanSecurities-EDU", broker: "DamanSecurities", isDemo: true },
    { name: "DanaGlobal-Server", broker: "DanaGlobal" },
    { name: "Darwinex-Demo", broker: "Darwinex", isDemo: true },
    { name: "Darwinex-Live", broker: "Darwinex" },
    { name: "DBGMarkets-Live", broker: "DBGMarkets" },
    { name: "DBGMarketsZA-Live", broker: "DBGMarketsZA" },
    { name: "DBInvest-Limited", broker: "DBInvest" },
    { name: "DecodeGlobal-Server", broker: "DecodeGlobal" },
    { name: "DefcoFX-Server", broker: "DefcoFX" },
    { name: "DeltaStock-Server", broker: "DeltaStock" },
    { name: "Deriv-Demo", broker: "Deriv", isDemo: true },
    { name: "Deriv-Server", broker: "Deriv" },
    { name: "Deriv-Server-02", broker: "Deriv" },
    { name: "Deriv-Server-03", broker: "Deriv" },
    { name: "DerivBVI-Demo", broker: "Deriv", isDemo: true },
    { name: "DerivBVI-Server", broker: "Deriv" },
    { name: "DerivBVI-Server-02", broker: "Deriv" },
    { name: "DerivBVI-Server-03", broker: "Deriv" },
    { name: "DerivFX-Demo", broker: "Deriv", isDemo: true },
    { name: "DerivFX-Server", broker: "Deriv" },
    { name: "DerivFX-Server-02", broker: "Deriv" },
    { name: "DerivFX-Server-03", broker: "Deriv" },
    { name: "DerivKY-Demo", broker: "Deriv", isDemo: true },
    { name: "DerivMT-Demo", broker: "Deriv", isDemo: true },
    { name: "DerivMT-Server", broker: "Deriv" },
    { name: "DerivMT-Server-02", broker: "Deriv" },
    { name: "DerivMT-Server-03", broker: "Deriv" },
    { name: "DerivMU-Server", broker: "Deriv" },
    { name: "DerivSVG-Demo", broker: "Deriv", isDemo: true },
    { name: "DerivSVG-Server", broker: "Deriv" },
    { name: "DerivSVG-Server-02", broker: "Deriv" },
    { name: "DerivSVG-Server-03", broker: "Deriv" },
    { name: "DerivUAE-Demo", broker: "Deriv", isDemo: true },
    { name: "DerivVU-Demo", broker: "Deriv", isDemo: true },
    { name: "DerivVU-Server", broker: "Deriv" },
    { name: "DerivVU-Server-02", broker: "Deriv" },
    { name: "DerivVU-Server-03", broker: "Deriv" },
    { name: "DesertRose-Server", broker: "DesertRose" },
    { name: "DigibitsNetwork-Live", broker: "IG" },
    { name: "DLSMarkets-Demo", broker: "DLSMarkets", isDemo: true },
    { name: "DNAFundedLtd-MT5", broker: "DNAFundedLtd" },
    { name: "DNAMarkets-MT5", broker: "DNAMarkets" },
    { name: "DominionFunding-Server", broker: "DominionFunding" },
    { name: "DominionMarkets-Live", broker: "DominionMarkets" },
    { name: "DooFinancialCY-Live", broker: "DooFinancialCY" },
    { name: "DooFinancialFutures-Trade", broker: "DooFinancialFutures" },
    { name: "DooGroup-Demo", broker: "DooGroup", isDemo: true },
    { name: "DooTechnology-Demo", broker: "DooTechnology", isDemo: true },
    { name: "DooTechnology-Live", broker: "DooTechnology" },
    { name: "DOTOEurope-Real", broker: "DOTOEurope" },
    { name: "DOTOGlobal-Real", broker: "DOTOGlobal" },
    { name: "DragonstoneForex-Live", broker: "DragonstoneForex" },
    { name: "Dukascopy-demo-mt5-1", broker: "Dukascopy", isDemo: true },
    { name: "DupoinFuturesID-Real", broker: "DupoinFuturesID" },
    { name: "DupoinMarkets-Real", broker: "DupoinMarkets" },
    { name: "E8Funding-Demo", broker: "E8Funding", isDemo: true },
    { name: "E8Markets-Server", broker: "E8Markets" },
    { name: "EarnBroker-Sharp ECN", broker: "EarnBroker" },
    { name: "Earnex-Trade", broker: "Earnex" },
    { name: "easyMarkets-Live", broker: "easyMarkets" },
    { name: "EBCFinancialGroupKM-Live01", broker: "EBCFinancialGroupKM" },
    { name: "EBCFinancialGroupKY-Demo", broker: "EBCFinancialGroupKY", isDemo: true },
    { name: "EBCFinancialGroupKY-Live01", broker: "EBCFinancialGroupKY" },
    { name: "EBCFinancialGroupUK-LIVE", broker: "EBCFinancialGroupUK" },
    { name: "ECMarkets-MT5-Live01", broker: "ECMarkets" },
    { name: "ECMarketsFinancial-MT5-Live04", broker: "ECMarketsFinancial" },
    { name: "ECMarketsLtd-MT5-Live03", broker: "ECMarketsLtd" },
    { name: "ECmarketsLtd-MT5-Live05", broker: "ECmarketsLtd" },
    { name: "ECmarketsLtd-MT5-Live06", broker: "ECmarketsLtd" },
    { name: "EFXPro-Live", broker: "EFXPro" },
    { name: "EGlobalTrade-Classic", broker: "EGlobalTrade" },
    { name: "EGlobalTrade-Demo", broker: "EGlobalTrade", isDemo: true },
    { name: "EGMLabsLtd-Live", broker: "EGMLabsLtd" },
    { name: "EGMSecurities-Demo", broker: "EGMSecurities", isDemo: true },
    { name: "EGMSecurities-Live", broker: "EGMSecurities" },
    { name: "Eightcap-Demo", broker: "Eightcap", isDemo: true },
    { name: "Eightcap-Live", broker: "Eightcap" },
    { name: "EightcapEU-Live", broker: "Eightcap" },
    { name: "EightcapGlobal-Live", broker: "Eightcap" },
    { name: "EightcapInternational-MT5", broker: "Eightcap" },
    { name: "EightPlusCapital-real", broker: "IG" },
    { name: "Elefin-trade", broker: "Elefin" },
    { name: "Elev8-Real2", broker: "Elev8" },
    { name: "emarmarkets-live", broker: "emarmarkets" },
    { name: "EmiraXMarkets-Server", broker: "XM" },
    { name: "EmpireFX-Main Server", broker: "EmpireFX" },
    { name: "EntropyPlayer-Demo", broker: "EntropyPlayer", isDemo: true },
    { name: "EoneCapital-Live", broker: "EoneCapital" },
    { name: "ePlanet-MT5", broker: "ePlanet" },
    { name: "EquitiBrokerageSC-Demo", broker: "EquitiBrokerageSC", isDemo: true },
    { name: "EquitiBrokerageSC-Live", broker: "EquitiBrokerageSC" },
    { name: "EquitiCapitalUK-Demo", broker: "EquitiCapitalUK", isDemo: true },
    { name: "EquitiSecurities-Demo", broker: "EquitiSecurities", isDemo: true },
    { name: "EquitiSecurities-Live", broker: "EquitiSecurities" },
    { name: "EquityEdge-Trade", broker: "EquityEdge" },
    { name: "Errante-Demo", broker: "Errante", isDemo: true },
    { name: "ErranteSC-Live", broker: "ErranteSC" },
    { name: "EsaFX-Server", broker: "EsaFX" },
    { name: "Eterwealth-Online", broker: "Eterwealth" },
    { name: "ETOMarkets-Server", broker: "ETOMarkets" },
    { name: "EurotradeInternational-Server-1", broker: "EurotradeInternational" },
    { name: "EurotradeSA-Server-1", broker: "EurotradeSA" },
    { name: "EvercrestFunding-Server", broker: "EvercrestFunding" },
    { name: "EXCAPrime-Demo", broker: "EXCAPrime", isDemo: true },
    { name: "ExclusiveMarkets-Demo", broker: "ExclusiveMarkets", isDemo: true },
    { name: "ExclusiveMarkets-Live", broker: "ExclusiveMarkets" },
    { name: "ExclusivePrime-Demo", broker: "ExclusivePrime", isDemo: true },
    { name: "EXMATrading-Demo", broker: "XM", isDemo: true },
    { name: "Exness-MT5Real", broker: "Exness" },
    { name: "Exness-MT5Real10", broker: "Exness" },
    { name: "Exness-MT5Real11", broker: "Exness" },
    { name: "Exness-MT5Real12", broker: "Exness" },
    { name: "Exness-MT5Real15", broker: "Exness" },
    { name: "Exness-MT5Real17", broker: "Exness" },
    { name: "Exness-MT5Real18", broker: "Exness" },
    { name: "Exness-MT5Real19", broker: "Exness" },
    { name: "Exness-MT5Real2", broker: "Exness" },
    { name: "Exness-MT5Real20", broker: "Exness" },
    { name: "Exness-MT5Real21", broker: "Exness" },
    { name: "Exness-MT5Real22", broker: "Exness" },
    { name: "Exness-MT5Real23", broker: "Exness" },
    { name: "Exness-MT5Real24", broker: "Exness" },
    { name: "Exness-MT5Real25", broker: "Exness" },
    { name: "Exness-MT5Real26", broker: "Exness" },
    { name: "Exness-MT5Real27", broker: "Exness" },
    { name: "Exness-MT5Real28", broker: "Exness" },
    { name: "Exness-MT5Real29", broker: "Exness" },
    { name: "Exness-MT5Real3", broker: "Exness" },
    { name: "Exness-MT5Real30", broker: "Exness" },
    { name: "Exness-MT5Real31", broker: "Exness" },
    { name: "Exness-MT5Real32", broker: "Exness" },
    { name: "Exness-MT5Real33", broker: "Exness" },
    { name: "Exness-MT5Real34", broker: "Exness" },
    { name: "Exness-MT5Real35", broker: "Exness" },
    { name: "Exness-MT5Real36", broker: "Exness" },
    { name: "Exness-MT5Real37", broker: "Exness" },
    { name: "Exness-MT5Real38", broker: "Exness" },
    { name: "Exness-MT5Real39", broker: "Exness" },
    { name: "Exness-MT5Real4", broker: "Exness" },
    { name: "Exness-MT5Real40", broker: "Exness" },
    { name: "Exness-MT5Real41", broker: "Exness" },
    { name: "exness-MT5Real42", broker: "Exness" },
    { name: "Exness-MT5Real46", broker: "Exness" },
    { name: "Exness-MT5Real5", broker: "Exness" },
    { name: "Exness-MT5Real51", broker: "Exness" },
    { name: "Exness-MT5Real6", broker: "Exness" },
    { name: "Exness-MT5Real7", broker: "Exness" },
    { name: "Exness-MT5Real8", broker: "Exness" },
    { name: "Exness-MT5Real9", broker: "Exness" },
    { name: "Exness-MT5Trial", broker: "Exness", isDemo: true },
    { name: "Exness-MT5Trial10", broker: "Exness", isDemo: true },
    { name: "Exness-MT5Trial11", broker: "Exness", isDemo: true },
    { name: "Exness-MT5Trial12", broker: "Exness", isDemo: true },
    { name: "Exness-MT5Trial14", broker: "Exness", isDemo: true },
    { name: "Exness-MT5Trial15", broker: "Exness", isDemo: true },
    { name: "Exness-MT5Trial16", broker: "Exness", isDemo: true },
    { name: "Exness-MT5Trial17", broker: "Exness", isDemo: true },
    { name: "Exness-MT5Trial2", broker: "Exness", isDemo: true },
    { name: "Exness-MT5Trial3", broker: "Exness", isDemo: true },
    { name: "Exness-MT5Trial5", broker: "Exness", isDemo: true },
    { name: "Exness-MT5Trial6", broker: "Exness", isDemo: true },
    { name: "Exness-MT5Trial7", broker: "Exness", isDemo: true },
    { name: "Exness-MT5Trial8", broker: "Exness", isDemo: true },
    { name: "Exness-MT5Trial9", broker: "Exness", isDemo: true },
    { name: "Exness-Real", broker: "Exness" },
    { name: "Exness-Real1", broker: "Exness" },
    { name: "Exness-Real10", broker: "Exness" },
    { name: "Exness-Real11", broker: "Exness" },
    { name: "Exness-Real12", broker: "Exness" },
    { name: "Exness-Real13", broker: "Exness" },
    { name: "Exness-Real14", broker: "Exness" },
    { name: "Exness-Real15", broker: "Exness" },
    { name: "Exness-Real16", broker: "Exness" },
    { name: "Exness-Real17", broker: "Exness" },
    { name: "Exness-Real18", broker: "Exness" },
    { name: "Exness-Real19", broker: "Exness" },
    { name: "Exness-Real2", broker: "Exness" },
    { name: "Exness-Real20", broker: "Exness" },
    { name: "Exness-Real21", broker: "Exness" },
    { name: "Exness-Real22", broker: "Exness" },
    { name: "Exness-Real23", broker: "Exness" },
    { name: "Exness-Real24", broker: "Exness" },
    { name: "Exness-Real25", broker: "Exness" },
    { name: "Exness-Real26", broker: "Exness" },
    { name: "Exness-Real27", broker: "Exness" },
    { name: "Exness-Real28", broker: "Exness" },
    { name: "Exness-Real29", broker: "Exness" },
    { name: "Exness-Real3", broker: "Exness" },
    { name: "Exness-Real30", broker: "Exness" },
    { name: "Exness-Real4", broker: "Exness" },
    { name: "Exness-Real5", broker: "Exness" },
    { name: "Exness-Real6", broker: "Exness" },
    { name: "Exness-Real7", broker: "Exness" },
    { name: "Exness-Real8", broker: "Exness" },
    { name: "Exness-Real9", broker: "Exness" },
    { name: "Exness-Trial", broker: "Exness", isDemo: true },
    { name: "Exness-Trial2", broker: "Exness", isDemo: true },
    { name: "ExnessBV-MT5Real", broker: "Exness" },
    { name: "ExnessBV-MT5Real10", broker: "Exness" },
    { name: "ExnessBV-MT5Real11", broker: "Exness" },
    { name: "ExnessBV-MT5Real12", broker: "Exness" },
    { name: "ExnessBV-MT5Real15", broker: "Exness" },
    { name: "ExnessBV-MT5Real2", broker: "Exness" },
    { name: "ExnessBV-MT5Real3", broker: "Exness" },
    { name: "ExnessBV-MT5Real5", broker: "Exness" },
    { name: "ExnessBV-MT5Real6", broker: "Exness" },
    { name: "ExnessBV-MT5Real7", broker: "Exness" },
    { name: "ExnessBV-MT5Real8", broker: "Exness" },
    { name: "ExnessBV-MT5Real9", broker: "Exness" },
    { name: "ExnessBV-MT5Trial", broker: "Exness", isDemo: true },
    { name: "ExnessBV-MT5Trial10", broker: "Exness", isDemo: true },
    { name: "ExnessBV-MT5Trial11", broker: "Exness", isDemo: true },
    { name: "ExnessBV-MT5Trial12", broker: "Exness", isDemo: true },
    { name: "ExnessBV-MT5Trial2", broker: "Exness", isDemo: true },
    { name: "ExnessBV-MT5Trial5", broker: "Exness", isDemo: true },
    { name: "ExnessBV-MT5Trial6", broker: "Exness", isDemo: true },
    { name: "ExnessBV-MT5Trial7", broker: "Exness", isDemo: true },
    { name: "ExnessBV-MT5Trial8", broker: "Exness", isDemo: true },
    { name: "ExnessBV-MT5Trial9", broker: "Exness", isDemo: true },
    { name: "ExnessCY-Demo", broker: "Exness", isDemo: true },
    { name: "ExnessCY-LP_Real1", broker: "Exness" },
    { name: "ExnessInvestmentBankLtd-Demo", broker: "Exness", isDemo: true },
    { name: "ExnessInvestmentBankLtd-LP_Real1", broker: "Exness" },
    { name: "ExnessJO-MT5Real2", broker: "Exness" },
    { name: "ExnessKE-MT5Real10", broker: "Exness" },
    { name: "ExnessKE-MT5Real21", broker: "Exness" },
    { name: "ExnessKE-MT5Real9", broker: "Exness" },
    { name: "ExnessKE-MT5Trial10", broker: "Exness", isDemo: true },
    { name: "ExnessKE-MT5Trial9", broker: "Exness", isDemo: true },
    { name: "ExnessMenaFinancial-MT5Real34", broker: "Exness" },
    { name: "ExnessMU-MT5Real8", broker: "Exness" },
    { name: "ExnessSC-MT5Real", broker: "Exness" },
    { name: "ExnessSC-MT5Real10", broker: "Exness" },
    { name: "ExnessSC-MT5Real15", broker: "Exness" },
    { name: "ExnessSC-MT5Real2", broker: "Exness" },
    { name: "ExnessSC-MT5Real3", broker: "Exness" },
    { name: "ExnessSC-MT5Real5", broker: "Exness" },
    { name: "ExnessSC-MT5Real6", broker: "Exness" },
    { name: "ExnessSC-MT5Real7", broker: "Exness" },
    { name: "ExnessSC-MT5Real9", broker: "Exness" },
    { name: "ExnessSC-MT5Trial10", broker: "Exness", isDemo: true },
    { name: "ExnessSC-MT5Trial8", broker: "Exness", isDemo: true },
    { name: "ExnessSC-MT5Trial9", broker: "Exness", isDemo: true },
    { name: "ExnessSCLtd-Demo", broker: "Exness", isDemo: true },
    { name: "ExnessSCLtd-LP_Real1", broker: "Exness" },
    { name: "ExnessUK-Demo", broker: "Exness", isDemo: true },
    { name: "ExnessUK-LP_Real1", broker: "Exness" },
    { name: "ExnessVG-MT5Real10", broker: "Exness" },
    { name: "ExnessVG-MT5Real11", broker: "Exness" },
    { name: "ExnessVG-MT5Real8", broker: "Exness" },
    { name: "ExnessVG-MT5Real9", broker: "Exness" },
    { name: "ExnessVG-MT5Trial3", broker: "Exness", isDemo: true },
    { name: "ExnessVG-MT5Trial6", broker: "Exness", isDemo: true },
    { name: "ExnessVG-MT5Trial9", broker: "Exness", isDemo: true },
    { name: "ExnessVGLtd-Demo", broker: "Exness", isDemo: true },
    { name: "ExnessVGLtd-LP_Real1", broker: "Exness" },
    { name: "FalconMarkets-Live", broker: "FalconMarkets" },
    { name: "FalconMarkets-Server", broker: "FalconMarkets" },
    { name: "FastOneGlobal-Live", broker: "FastOneGlobal" },
    { name: "FazoFxLiquidity-Server", broker: "FazoFxLiquidity" },
    { name: "FBKMarkets-Live", broker: "FBKMarkets" },
    { name: "FBS-Demo", broker: "FBS", isDemo: true },
    { name: "FBS-Real", broker: "FBS" },
    { name: "FBSOceania-Real", broker: "FBSOceania" },
    { name: "FBSTradestone-Demo", broker: "FBSTradestone", isDemo: true },
    { name: "FBSTradestone-Real", broker: "FBSTradestone" },
    { name: "FBSTradingSeychelles-Real", broker: "FBSTradingSeychelles" },
    { name: "FeneFX-Server", broker: "FeneFX" },
    { name: "FHXmarkets-Trade", broker: "XM" },
    { name: "FIBOGroup-MT5 Server", broker: "FIBOGroup" },
    { name: "FinaltoAustralia-Live7", broker: "FinaltoAustralia" },
    { name: "FinaltoBVI-Live", broker: "FinaltoBVI" },
    { name: "FinaltoEU-Live7", broker: "FinaltoEU" },
    { name: "FinaltoUK-Live7", broker: "FinaltoUK" },
    { name: "FinexBisnisSolusi-Demo", broker: "FinexBisnisSolusi", isDemo: true },
    { name: "FinexBisnisSolusi-Real", broker: "FinexBisnisSolusi" },
    { name: "FinotiveMarkets-Live", broker: "FinotiveMarkets" },
    { name: "FinowizFintech-Live", broker: "FinowizFintech" },
    { name: "FinQuotesFinancialCY-Real", broker: "FinQuotesFinancialCY" },
    { name: "FinsaiTrade-Server", broker: "FinsaiTrade" },
    { name: "Fintokei-MT5-Server1", broker: "Fintokei" },
    { name: "Fintrix-Live", broker: "Fintrix" },
    { name: "FirstPrudentialMarkets-Demo", broker: "FirstPrudentialMarkets", isDemo: true },
    { name: "FirstPrudentialMarkets-Live", broker: "FirstPrudentialMarkets" },
    { name: "FirstPrudentialMarketsCY-Live", broker: "FirstPrudentialMarketsCY" },
    { name: "FivePercentOnline-Experience", broker: "FivePercentOnline" },
    { name: "FivePercentOnline-Real", broker: "FivePercentOnline" },
    { name: "FizmoFxMarkets-Server", broker: "XM" },
    { name: "FNmarkets-Server", broker: "FNmarkets" },
    { name: "FNmarketsMU-Server", broker: "FNmarketsMU" },
    { name: "FocusMarkets-Demo", broker: "FocusMarkets", isDemo: true },
    { name: "Foraxis-Trade", broker: "Axi" },
    { name: "ForeignExchangeClearingHouse-Main", broker: "IG" },
    { name: "Forex.com-Demo 535", broker: "FOREX.com", isDemo: true },
    { name: "Forex.com-Live 536", broker: "FOREX.com" },
    { name: "FOREX.comCA-Demo 531", broker: "FOREX.com", isDemo: true },
    { name: "FOREX.comCA-Live 532", broker: "FOREX.com" },
    { name: "FOREX.comEurope-Live 532", broker: "FOREX.com" },
    { name: "FOREX.comGlobal-Demo 531", broker: "FOREX.com", isDemo: true },
    { name: "FOREX.comGlobalCN-Demo 533", broker: "FOREX.com", isDemo: true },
    { name: "FOREX.comGlobalCN-Live 534", broker: "FOREX.com" },
    { name: "Forex.comJP-Live 534", broker: "FOREX.com" },
    { name: "Forexcitypro-Live", broker: "Forexcitypro" },
    { name: "ForexClub-MT5 Instant Real Server", broker: "ForexClub" },
    { name: "ForexClub-MT5 Real Server", broker: "ForexClub" },
    { name: "ForexClubInternational-MT5 Demo", broker: "ForexClubInternational", isDemo: true },
    { name: "ForexClubInternational-MT5 Market Real 2", broker: "ForexClubInternational" },
    { name: "ForexTime-Demo01", broker: "ForexTime", isDemo: true },
    { name: "ForexTime-Live01", broker: "ForexTime" },
    { name: "ForexTimeFXTM-Demo01", broker: "FXTM", isDemo: true },
    { name: "ForexTimeFXTM-Demo02", broker: "FXTM", isDemo: true },
    { name: "ForexTimeFXTM-Live01", broker: "FXTM" },
    { name: "FortressFX-Trade", broker: "FortressFX" },
    { name: "FortunePrime-Demo2", broker: "FortunePrime", isDemo: true },
    { name: "FortunePrime-Live2", broker: "FortunePrime" },
    { name: "FortunePrimeGlobal-Demo", broker: "FortunePrimeGlobal", isDemo: true },
    { name: "FotMarkets-Server", broker: "FotMarkets" },
    { name: "FoundstoneGlobalWealth-Server", broker: "FoundstoneGlobalWealth" },
    { name: "FPMarkets-Demo", broker: "FP Markets", isDemo: true },
    { name: "FPMarkets-Demo2", broker: "FP Markets", isDemo: true },
    { name: "FPMarkets-Live", broker: "FP Markets" },
    { name: "FPMarkets-Live2", broker: "FP Markets" },
    { name: "FPMarketsKE-Demo", broker: "FP Markets", isDemo: true },
    { name: "FPMarketsLLC-Demo", broker: "FP Markets", isDemo: true },
    { name: "FPMarketsLLC-Live", broker: "FP Markets" },
    { name: "FPMarketsLtd-Demo2", broker: "FP Markets", isDemo: true },
    { name: "FPMarketsLtd-Live2", broker: "FP Markets" },
    { name: "FPMarketsSC-Demo", broker: "FP Markets", isDemo: true },
    { name: "FPMarketsSC-Live", broker: "FP Markets" },
    { name: "FPMTrading-Demo", broker: "FPMTrading", isDemo: true },
    { name: "FPMTrading-Live", broker: "FPMTrading" },
    { name: "FPtradingLLC-Live", broker: "FPtradingLLC" },
    { name: "FreshForex-MT5", broker: "FreshForex" },
    { name: "FTMO-Demo", broker: "FTMO", isDemo: true },
    { name: "FTMO-Demo2", broker: "FTMO", isDemo: true },
    { name: "FTMO-Server", broker: "FTMO" },
    { name: "FTMO-Server2", broker: "FTMO" },
    { name: "FTMO-Server3", broker: "FTMO" },
    { name: "FTMO-Server4", broker: "FTMO" },
    { name: "FTMO-Server5", broker: "FTMO" },
    { name: "FTTrading-Server", broker: "FTTrading" },
    { name: "FTUKMarkets-Live", broker: "FTUKMarkets" },
    { name: "FTUKMarkets-Trade", broker: "FTUKMarkets" },
    { name: "Funded7-Funded7", broker: "Funded7" },
    { name: "Fundedelite-Server", broker: "Fundedelite" },
    { name: "FundedFirm-Live", broker: "FundedFirm" },
    { name: "FundedFriday-Trade", broker: "FundedFriday" },
    { name: "FundedNext-Server", broker: "FundedNext" },
    { name: "FundedNext-Server 2", broker: "FundedNext" },
    { name: "FundedNext-Server 3", broker: "FundedNext" },
    { name: "FundedNext-Server 4", broker: "FundedNext" },
    { name: "FundedSquad-server", broker: "FundedSquad" },
    { name: "FundedTraderMarkets-Server", broker: "FundedTraderMarkets" },
    { name: "FundedTradingPlus-Live", broker: "FundedTradingPlus" },
    { name: "FundedVerse-Server", broker: "FundedVerse" },
    { name: "FunderPro-Live01", broker: "FunderPro" },
    { name: "FundingPips-Server", broker: "Funding Pips" },
    { name: "FundingPips-SIM", broker: "Funding Pips" },
    { name: "FundingPips-SIM1", broker: "Funding Pips" },
    { name: "FundingPips-Trial", broker: "Funding Pips", isDemo: true },
    { name: "FundingPips2-SIM", broker: "Funding Pips" },
    { name: "FundingTradersGroup-Server", broker: "FundingTradersGroup" },
    { name: "FundsCap-Trade", broker: "FundsCap" },
    { name: "FusionMarkets-Demo", broker: "FusionMarkets", isDemo: true },
    { name: "FusionMarkets-Live", broker: "FusionMarkets" },
    { name: "FusionMarketsAU-Demo", broker: "FusionMarketsAU", isDemo: true },
    { name: "FusionMarketsAU-Live", broker: "FusionMarketsAU" },
    { name: "FusionMarketsInternational-MT5_2", broker: "FusionMarketsInternational" },
    { name: "FXCC1-Trade", broker: "FXCC1" },
    { name: "FXFigFinancial-Server", broker: "IG" },
    { name: "FXGlobeInternational-Real", broker: "FXGlobeInternational" },
    { name: "FXGT-Live", broker: "FXGT" },
    { name: "FXIFY-Server", broker: "FXIFY" },
    { name: "FxLiveCapital-Server", broker: "FxLiveCapital" },
    { name: "FXnity-Server", broker: "FXnity" },
    { name: "FXNXGlobal-Trade", broker: "FXNXGlobal" },
    { name: "FXOpenEU-MT5", broker: "FXOpen" },
    { name: "FXOroGlobal-Trade", broker: "FXOroGlobal" },
    { name: "FXPIG-Server", broker: "IG" },
    { name: "FxPro-MT5", broker: "FxPro" },
    { name: "FxPro-MT5 Demo", broker: "FxPro", isDemo: true },
    { name: "FxPro-MT5 Live02", broker: "FxPro" },
    { name: "fxpro-mt5 live03", broker: "fxpro" },
    { name: "FxPro.Global-MT5 Live02", broker: "FxPro.Global" },
    { name: "FXRKMarkets-Server", broker: "FXRKMarkets" },
    { name: "FXTRADING.com-Demo", broker: "FXTRADING.com", isDemo: true },
    { name: "FXView-Demo", broker: "FXView", isDemo: true },
    { name: "FXView-Live", broker: "FXView" },
    { name: "FXView2-Demo", broker: "FXView2", isDemo: true },
    { name: "FXView2-Live", broker: "FXView2" },
    { name: "GatesFX-Live", broker: "GatesFX" },
    { name: "GBEbrokers-Demo", broker: "GBEbrokers", isDemo: true },
    { name: "GBEbrokers-LIVE", broker: "GBEbrokers" },
    { name: "GerchikCo-MT5", broker: "GerchikCo" },
    { name: "GetLeveraged-Trade", broker: "GetLeveraged" },
    { name: "GlobalBuanaKarya-Live", broker: "GlobalBuanaKarya" },
    { name: "GlobalDynamicMarkets-Demo", broker: "IC Markets", isDemo: true },
    { name: "GlobalFuturesServices-Server", broker: "GlobalFuturesServices" },
    { name: "GlobalPrime-Demo", broker: "GlobalPrime", isDemo: true },
    { name: "GlobalPrime-Trade", broker: "GlobalPrime" },
    { name: "GNTCapital-Demo", broker: "GNTCapital", isDemo: true },
    { name: "GNTCapital-Live", broker: "GNTCapital" },
    { name: "GoatFunded-Server", broker: "GoatFunded" },
    { name: "GoatFunded-Server2", broker: "GoatFunded" },
    { name: "GoatFunded-Server3", broker: "GoatFunded" },
    { name: "GOCPrime-Server", broker: "GOCPrime" },
    { name: "GoDo-Server", broker: "GoDo" },
    { name: "GOFX-Real", broker: "GOFX" },
    { name: "GoldenFortuneDerivatives-Server", broker: "Deriv" },
    { name: "GoldStocksFx-Server", broker: "GoldStocksFx" },
    { name: "GoMarkets-Demo", broker: "GoMarkets", isDemo: true },
    { name: "GOMarketsIntl-Demo", broker: "GOMarketsIntl", isDemo: true },
    { name: "GOMarketsLtd-Live", broker: "GOMarketsLtd" },
    { name: "GOMarketsMU-Live", broker: "GOMarketsMU" },
    { name: "GOMarketsSVG-Live", broker: "GOMarketsSVG" },
    { name: "GracexFx-Server", broker: "GracexFx" },
    { name: "GreatBright-Server", broker: "IG" },
    { name: "GreatGoldenBrilliant-Trade", broker: "GreatGoldenBrilliant" },
    { name: "GrupoInteligencia-Server", broker: "IG" },
    { name: "GrupoInteligenciaSpA-Server", broker: "IG" },
    { name: "GTCGlobalTrade-Server", broker: "GTCGlobalTrade" },
    { name: "GustoFortune-LIVE", broker: "GustoFortune" },
    { name: "GVDKorimcy-Server", broker: "GVDKorimcy" },
    { name: "HantecAU-LIVE", broker: "HantecAU" },
    { name: "HantecMarkets-MT5", broker: "HantecMarkets" },
    { name: "HantecMarketsMU-MT5", broker: "HantecMarketsMU" },
    { name: "HantecMarketsUK-MT5", broker: "HantecMarketsUK" },
    { name: "HantecMarketsV-LIVE", broker: "HantecMarketsV" },
    { name: "Headway-Demo", broker: "Headway", isDemo: true },
    { name: "Headway-Real", broker: "Headway" },
    { name: "HeroFX-Trade", broker: "HeroFX" },
    { name: "HFMarkets-Demo", broker: "HFM", isDemo: true },
    { name: "HFMarkets-Live1", broker: "HFM" },
    { name: "HFMarketsEurope-Demo2", broker: "HFM", isDemo: true },
    { name: "HFMarketsEurope-Live2", broker: "HFM" },
    { name: "HFMarketsGlobal-Demo", broker: "HFM", isDemo: true },
    { name: "HFMarketsGlobal-Demo4", broker: "HFM", isDemo: true },
    { name: "HFMarketsGlobal-Live1", broker: "HFM" },
    { name: "HFMarketsGlobal-Live10", broker: "HFM" },
    { name: "HFMarketsGlobal-Live11", broker: "HFM" },
    { name: "HFMarketsGlobal-Live12", broker: "HFM" },
    { name: "HFMarketsGlobal-Live13", broker: "HFM" },
    { name: "HFMarketsGlobal-Live14", broker: "HFM" },
    { name: "HFMarketsGlobal-Live15", broker: "HFM" },
    { name: "HFMarketsGlobal-Live16", broker: "HFM" },
    { name: "HFMarketsGlobal-Live17", broker: "HFM" },
    { name: "HFMarketsGlobal-Live18", broker: "HFM" },
    { name: "HFMarketsGlobal-Live19", broker: "HFM" },
    { name: "HFMarketsGlobal-Live20", broker: "HFM" },
    { name: "HFMarketsGlobal-Live3", broker: "HFM" },
    { name: "HFMarketsGlobal-Live4", broker: "HFM" },
    { name: "HFMarketsGlobal-Live5", broker: "HFM" },
    { name: "HFMarketsGlobal-Live7", broker: "HFM" },
    { name: "HFMarketsGlobal-Live8", broker: "HFM" },
    { name: "HFMarketsGlobal-Live9", broker: "HFM" },
    { name: "HFMarketsKE-Demo2", broker: "HFM", isDemo: true },
    { name: "HFMarketsKE-Live11", broker: "HFM" },
    { name: "HFMarketsKE-Live2", broker: "HFM" },
    { name: "HFMarketsMENA-Demo2", broker: "HFM", isDemo: true },
    { name: "HFMarketsSA-Demo2", broker: "HFM", isDemo: true },
    { name: "HFMarketsSA-Live1", broker: "HFM" },
    { name: "HFMarketsSA-Live10", broker: "HFM" },
    { name: "HFMarketsSA-Live11", broker: "HFM" },
    { name: "HFMarketsSA-Live14", broker: "HFM" },
    { name: "HFMarketsSA-Live2", broker: "HFM" },
    { name: "HFMarketsSA1-Demo2", broker: "HFM", isDemo: true },
    { name: "HFMarketsSA1-Live2", broker: "HFM" },
    { name: "HFMarketsSC-Demo", broker: "HFM", isDemo: true },
    { name: "HFMarketsSC-Live", broker: "HFM" },
    { name: "HFMarketsSC-Live14", broker: "HFM" },
    { name: "HFMarketsSC-Live2", broker: "HFM" },
    { name: "HFMarketsUK-Live2", broker: "HFM" },
    { name: "HighnessInvest-Server", broker: "IG" },
    { name: "HighRiseMarket-LIVE", broker: "IG" },
    { name: "HijaGlobalMarkets-Server", broker: "HijaGlobalMarkets" },
    { name: "Holaprime-Server1", broker: "Holaprime" },
    { name: "HYCM-Live", broker: "HYCM" },
    { name: "ICFundedEvaluations-MT5-Demo ICFundedEvaluations02", broker: "ICFundedEvaluations", isDemo: true },
    { name: "ICMarkets-Demo", broker: "IC Markets", isDemo: true },
    { name: "ICMarkets-MT5-2", broker: "IC Markets" },
    { name: "ICMarkets-MT5-4", broker: "IC Markets" },
    { name: "ICMarketsAU-Live", broker: "IC Markets" },
    { name: "ICMarketsEU-Demo", broker: "IC Markets", isDemo: true },
    { name: "ICMarketsEU-MT5-5", broker: "IC Markets" },
    { name: "ICMarketsGRP-Demo", broker: "IC Markets", isDemo: true },
    { name: "ICMarketsInternational-Demo", broker: "IC Markets", isDemo: true },
    { name: "ICMarketsInternational-MT5-2", broker: "IC Markets" },
    { name: "ICMarketsKE-Demo", broker: "IC Markets", isDemo: true },
    { name: "ICMarketsKE-MT5-7", broker: "IC Markets" },
    { name: "ICMarketsKY-MT5-4", broker: "IC Markets" },
    { name: "ICMarketsSC-Demo", broker: "IC Markets", isDemo: true },
    { name: "ICMarketsSC-Demo02", broker: "IC Markets", isDemo: true },
    { name: "ICMarketsSC-Live01", broker: "IC Markets" },
    { name: "ICMarketsSC-Live02", broker: "IC Markets" },
    { name: "ICMarketsSC-Live03", broker: "IC Markets" },
    { name: "ICMarketsSC-Live04", broker: "IC Markets" },
    { name: "ICMarketsSC-Live05", broker: "IC Markets" },
    { name: "ICMarketsSC-Live06", broker: "IC Markets" },
    { name: "ICMarketsSC-Live07", broker: "IC Markets" },
    { name: "ICMarketsSC-Live08", broker: "IC Markets" },
    { name: "ICMarketsSC-Live09", broker: "IC Markets" },
    { name: "ICMarketsSC-Live10", broker: "IC Markets" },
    { name: "ICMarketsSC-Live11", broker: "IC Markets" },
    { name: "ICMarketsSC-Live12", broker: "IC Markets" },
    { name: "ICMarketsSC-Live13", broker: "IC Markets" },
    { name: "ICMarketsSC-Live14", broker: "IC Markets" },
    { name: "ICMarketsSC-Live15", broker: "IC Markets" },
    { name: "ICMarketsSC-Live16", broker: "IC Markets" },
    { name: "ICMarketsSC-Live17", broker: "IC Markets" },
    { name: "ICMarketsSC-Live18", broker: "IC Markets" },
    { name: "ICMarketsSC-Live19", broker: "IC Markets" },
    { name: "ICMarketsSC-Live20", broker: "IC Markets" },
    { name: "ICMarketsSC-MT5", broker: "IC Markets" },
    { name: "ICMarketsSC-MT5-2", broker: "IC Markets" },
    { name: "ICMarketsSC-MT5-3", broker: "IC Markets" },
    { name: "ICMarketsSC-MT5-4", broker: "IC Markets" },
    { name: "Icmarketssc-mt5-6", broker: "IC Markets" },
    { name: "ICMCapital-Demo", broker: "ICMCapital", isDemo: true },
    { name: "ICTrading-Demo", broker: "ICTrading", isDemo: true },
    { name: "ICTrading-MT5-2", broker: "ICTrading" },
    { name: "ICTrading-MT5-4", broker: "ICTrading" },
    { name: "IDFXFutures-Live", broker: "IDFXFutures" },
    { name: "IEXS-Live", broker: "IEXS" },
    { name: "IFCMarkets-Demo", broker: "IFCMarkets", isDemo: true },
    { name: "IFPro-Trade", broker: "IFPro" },
    { name: "iFunds-Server", broker: "iFunds" },
    { name: "IFXBrokers-Real", broker: "IFXBrokers" },
    { name: "IG-DEMO", broker: "IG", isDemo: true },
    { name: "IGBMarkets-Server", broker: "IG" },
    { name: "ImperialSolutions-Demo", broker: "ImperialSolutions", isDemo: true },
    { name: "ImpulseWorldCorp-Server", broker: "ImpulseWorldCorp" },
    { name: "Indigosoft-Brokerpilot MT5", broker: "IG" },
    { name: "InfinoxCapitalLimited-MT5Demo", broker: "InfinoxCapitalLimited", isDemo: true },
    { name: "InfinoxCapitalLimited-MT5Live", broker: "InfinoxCapitalLimited" },
    { name: "InfinoxLimited-MT5Demo", broker: "InfinoxLimited", isDemo: true },
    { name: "InfinoxLimited-MT5Live", broker: "InfinoxLimited" },
    { name: "IngotBrokers-Server", broker: "IngotBrokers" },
    { name: "INGOTGlobalLtd-Server", broker: "INGOTGlobalLtd" },
    { name: "INGOTSC-Server", broker: "INGOTSC" },
    { name: "instaforex-Server", broker: "instaforex" },
    { name: "InstitutionalTrading-MT5", broker: "InstitutionalTrading" },
    { name: "IntelligentQuantum-Server", broker: "IG" },
    { name: "InterPanPasifik-Live", broker: "InterPanPasifik" },
    { name: "InterStellarFinancial-Server", broker: "InterStellarFinancial" },
    { name: "InterTrader-Server", broker: "InterTrader" },
    { name: "Invadigm-Live", broker: "IG" },
    { name: "Investizo-universal", broker: "Investizo" },
    { name: "invidiatrade-Live", broker: "invidiatrade" },
    { name: "Inzo-Live", broker: "Inzo" },
    { name: "IronFX-Real1", broker: "IronFX" },
    { name: "IS6Technologies-Live", broker: "IS6Technologies" },
    { name: "IUXMarkets-Demo", broker: "XM", isDemo: true },
    { name: "IUXMarkets-Live", broker: "XM" },
    { name: "IUXMarkets-Live3", broker: "XM" },
    { name: "IUXMarketsMU-Live", broker: "XM" },
    { name: "JavaGlobalFutures-Live", broker: "JavaGlobalFutures" },
    { name: "JFD-Demo", broker: "JFD", isDemo: true },
    { name: "JFDOverseas-Live", broker: "JFDOverseas" },
    { name: "JMFinancial-Server", broker: "JMFinancial" },
    { name: "JPMarkets-Live", broker: "JPMarkets" },
    { name: "JTMarkets-Trade", broker: "JTMarkets" },
    { name: "JunoMarkets-Live", broker: "JunoMarkets" },
    { name: "Just2Trade-MT5", broker: "Just2Trade" },
    { name: "JustForex-Demo", broker: "JustForex", isDemo: true },
    { name: "JustForex-Live", broker: "JustForex" },
    { name: "JustMarkets-Demo", broker: "JustMarkets", isDemo: true },
    { name: "JustMarkets-Demo2", broker: "JustMarkets", isDemo: true },
    { name: "JustMarkets-Demo3", broker: "JustMarkets", isDemo: true },
    { name: "JustMarkets-Live", broker: "JustMarkets" },
    { name: "JustMarkets-Live2", broker: "JustMarkets" },
    { name: "JustMarkets-Live3", broker: "JustMarkets" },
    { name: "JustMarkets-Live6", broker: "JustMarkets" },
    { name: "JustMarketsCY-Demo", broker: "JustMarkets", isDemo: true },
    { name: "JustMarketsCY-Live", broker: "JustMarkets" },
    { name: "KatoPrime-Live", broker: "KatoPrime" },
    { name: "KCMTrade-Live", broker: "KCMTrade" },
    { name: "KeytoMarkets-Server", broker: "KeytoMarkets" },
    { name: "KiraFinancialBrokers-Live", broker: "KiraFinancialBrokers" },
    { name: "KnightMarkets-Server", broker: "IG" },
    { name: "KohleCapitalMarkets-Live", broker: "KohleCapitalMarkets" },
    { name: "Kudotrade-Live", broker: "Kudotrade" },
    { name: "KVBPrimeLimited-Real", broker: "KVBPrimeLimited" },
    { name: "KwakolMarketsPty-Server", broker: "KwakolMarketsPty" },
    { name: "LangitIndonesia-MT5-Live", broker: "LangitIndonesia" },
    { name: "LegacyFX-Server", broker: "LegacyFX" },
    { name: "LeverageMarkets-Trade", broker: "LeverageMarkets" },
    { name: "LHFXSA-Trade", broker: "LHFXSA" },
    { name: "LibertexCom-MT5 Demo Server", broker: "LibertexCom", isDemo: true },
    { name: "LibertexMU-MT5 Demo", broker: "XM", isDemo: true },
    { name: "LibertexMU-MT5 Market Real 2", broker: "XM" },
    { name: "LibertyMarkets-Server", broker: "LibertyMarkets" },
    { name: "LightonManagement-Server", broker: "IG" },
    { name: "LightSpectrumExecution-Live", broker: "IG" },
    { name: "LiquidMarkets-Server", broker: "LiquidMarkets" },
    { name: "LirunexLimited-Live-MT5", broker: "LirunexLimited" },
    { name: "LiteFinance-MT5-Demo", broker: "LiteFinance", isDemo: true },
    { name: "LiteFinance-MT5-Live", broker: "LiteFinance" },
    { name: "LiteForexEU-MT5-Live", broker: "LiteForexEU" },
    { name: "LLAGlobalMarkets-Live", broker: "LLAGlobalMarkets" },
    { name: "LordPrime-Global", broker: "LordPrime" },
    { name: "LotusFX-Demo", broker: "LotusFX", isDemo: true },
    { name: "LoyalPrimusPty-Server", broker: "LoyalPrimusPty" },
    { name: "LQHIntegrated-Server", broker: "LQHIntegrated" },
    { name: "LunaroFinancialServices-MainTrade", broker: "LunaroFinancialServices" },
    { name: "LuxTradingFirm-Server", broker: "LuxTradingFirm" },
    { name: "M4Markets-MT5", broker: "M4Markets" },
    { name: "MacroMarketsHK-Live", broker: "MacroMarketsHK" },
    { name: "MagicCompass-live", broker: "MagicCompass" },
    { name: "Mahadana-Primary", broker: "Mahadana" },
    { name: "MajestyFX-Trade", broker: "MajestyFX" },
    { name: "MakeCapital-Live", broker: "MakeCapital" },
    { name: "MakroFX-Demo", broker: "MakroFX", isDemo: true },
    { name: "MandiriInvestindo-Server", broker: "MandiriInvestindo" },
    { name: "MaonoGlobalMarkets-Live", broker: "MaonoGlobalMarkets" },
    { name: "MarketFinancials-MT5", broker: "MarketFinancials" },
    { name: "Marketmates-live", broker: "Marketmates" },
    { name: "Markets.com-Live", broker: "Markets.com" },
    { name: "MarketsVox-Demo", broker: "MarketsVox", isDemo: true },
    { name: "MarketsVox-Live", broker: "MarketsVox" },
    { name: "MavenTrade-Server", broker: "MavenTrade" },
    { name: "MaxifyFX-Live", broker: "Axi" },
    { name: "MaxiMarket-MEXC-LIVE-1", broker: "Axi" },
    { name: "MaximusGlobal-Real", broker: "Axi" },
    { name: "MaziMaticFinancial-Server", broker: "MaziMaticFinancial" },
    { name: "MBFXGlobal-Server", broker: "MBFXGlobal" },
    { name: "MegaFusionGroupPty-Trade", broker: "MegaFusionGroupPty" },
    { name: "MerlionGlobal-Live", broker: "MerlionGlobal" },
    { name: "Metagold-Server", broker: "Metagold" },
    { name: "MetaQuotes-Demo", broker: "MetaQuotes", isDemo: true },
    { name: "MEXAtlantic-Demo", broker: "MEXAtlantic", isDemo: true },
    { name: "MEXAtlantic-Real", broker: "MEXAtlantic" },
    { name: "MEXDigital-Live", broker: "IG" },
    { name: "MEXGlobalFinancial-Real", broker: "MEXGlobalFinancial" },
    { name: "MidoriFX-LIVE", broker: "MidoriFX" },
    { name: "MilesCapital-Server", broker: "MilesCapital" },
    { name: "MohicansMarkets-Live", broker: "MohicansMarkets" },
    { name: "Monaxa-Demo", broker: "Monaxa", isDemo: true },
    { name: "Monaxa-MT5", broker: "Monaxa" },
    { name: "Mondtrades-Server", broker: "Mondtrades" },
    { name: "Monetafunded-Live", broker: "Monetafunded" },
    { name: "MonetaMarkets-Demo", broker: "MonetaMarkets", isDemo: true },
    { name: "MonetaMarkets-Live", broker: "MonetaMarkets" },
    { name: "MonetaMarketsTrading-Live", broker: "MonetaMarketsTrading" },
    { name: "MonevisBrokers-Live", broker: "MonevisBrokers" },
    { name: "Monex-Demo", broker: "Monex", isDemo: true },
    { name: "Monex-Live", broker: "Monex" },
    { name: "MOTCapital-Demo-1", broker: "MOTCapital", isDemo: true },
    { name: "MOTCapital-Live-1", broker: "MOTCapital" },
    { name: "MOTForex-Demo-1", broker: "MOTForex", isDemo: true },
    { name: "MoyaMarkets-Server", broker: "MoyaMarkets" },
    { name: "MRGMega-Primary", broker: "MRGMega" },
    { name: "MTrading-Live", broker: "MTrading" },
    { name: "MultiBankFX-Real", broker: "MultiBankFX" },
    { name: "MultiLPCompany-Server", broker: "MultiLPCompany" },
    { name: "MultiStockTrading-Live", broker: "MultiStockTrading" },
    { name: "Murrentrade-Online", broker: "Murrentrade" },
    { name: "MyFXMarkets-Live", broker: "XM" },
    { name: "MyMaaMarkets-Server", broker: "MyMaaMarkets" },
    { name: "MysSuccessfulConnect-Server", broker: "MysSuccessfulConnect" },
    { name: "N1CapitalMarkets-Live", broker: "N1CapitalMarkets" },
    { name: "Naga.comAE-Demo", broker: "Naga.comAE", isDemo: true },
    { name: "NAGACapital-Demo", broker: "NAGACapital", isDemo: true },
    { name: "NagaMarkets-Demo", broker: "NagaMarkets", isDemo: true },
    { name: "NarruxDigitalAssets-Server", broker: "IG" },
    { name: "NCMInvestmentKW-Demo", broker: "NCMInvestmentKW", isDemo: true },
    { name: "NCMInvestmentMenkul-Real", broker: "NCMInvestmentMenkul" },
    { name: "Neex-Live 2", broker: "Neex" },
    { name: "NeolinCapitalMarket-Server", broker: "NeolinCapitalMarket" },
    { name: "Neomaaa-Global", broker: "Neomaaa" },
    { name: "Neomaaa-Live", broker: "Neomaaa" },
    { name: "Neomarkets-Live", broker: "Neomarkets" },
    { name: "NeonMarkets-Server", broker: "NeonMarkets" },
    { name: "Nexo-Server", broker: "Nexo" },
    { name: "NextlevelTrade-Server", broker: "NextlevelTrade" },
    { name: "NGFunding-Trade", broker: "NGFunding" },
    { name: "Noctorial-Trade", broker: "Noctorial" },
    { name: "NoorAlmal-Real", broker: "NoorAlmal" },
    { name: "NoorCapitalUK-Multi Assets", broker: "NoorCapitalUK" },
    { name: "NordFX-Real", broker: "NordFX" },
    { name: "Nosscompany-Server", broker: "Nosscompany" },
    { name: "NostroMarkets-Trade", broker: "NostroMarkets" },
    { name: "Nozax-Trade", broker: "Nozax" },
    { name: "NozaxAD-Trade", broker: "NozaxAD" },
    { name: "NPEMarket-Real", broker: "NPEMarket" },
    { name: "NuvestoMarkets-Nuvesto1", broker: "NuvestoMarkets" },
    { name: "NXGMarkets-Server", broker: "NXGMarkets" },
    { name: "NYSMarketsLtd-trade", broker: "NYSMarketsLtd" },
    { name: "OANDA-Demo-1", broker: "OANDA", isDemo: true },
    { name: "OANDA-Japan MT5 Live", broker: "OANDA" },
    { name: "OANDA-Live-1", broker: "OANDA" },
    { name: "OANDA-Prop Trader", broker: "OANDA" },
    { name: "OANDA_AU-Demo-1", broker: "OANDA", isDemo: true },
    { name: "OANDA_Canada-Demo-1", broker: "OANDA", isDemo: true },
    { name: "OANDA_Global-Live-1", broker: "OANDA" },
    { name: "OANDA_SG-Demo-1", broker: "OANDA", isDemo: true },
    { name: "Oanda_UK-Live-1", broker: "OANDA" },
    { name: "OANDATMS-MT5", broker: "OANDA" },
    { name: "OceanMarkets-Server", broker: "OceanMarkets" },
    { name: "OCIOasisCapital-Live", broker: "OCIOasisCapital" },
    { name: "OctaCy-Real", broker: "OctaCy" },
    { name: "OctaFX-Demo", broker: "OctaFX", isDemo: true },
    { name: "OctaFX-Real", broker: "OctaFX" },
    { name: "OctaFX-Real2", broker: "OctaFX" },
    { name: "OctaInvestama2-Server", broker: "OctaInvestama2" },
    { name: "OctaMarkets-Demo", broker: "OctaMarkets", isDemo: true },
    { name: "OEXNLimited-Demo", broker: "OEXNLimited", isDemo: true },
    { name: "OFPFunding-Trade", broker: "OFPFunding" },
    { name: "OGMInternational-Server", broker: "OGMInternational" },
    { name: "OmniMarkets-OFinancial", broker: "OmniMarkets" },
    { name: "OnamTrading-Live", broker: "OnamTrading" },
    { name: "OneFinancialMarkets-US48-Live", broker: "OneFinancialMarkets" },
    { name: "ONEFUNDED-TRADE", broker: "ONEFUNDED" },
    { name: "OnEquity-Server", broker: "OnEquity" },
    { name: "OnEquityMU-Server", broker: "OnEquityMU" },
    { name: "OneRoyal-Demo", broker: "OneRoyal", isDemo: true },
    { name: "OneRoyal-Server", broker: "OneRoyal" },
    { name: "Opogroup-Server1", broker: "Opogroup" },
    { name: "OpogroupLLC-Server2", broker: "OpogroupLLC" },
    { name: "OptimalTraders-Server", broker: "OptimalTraders" },
    { name: "OQtima-Live", broker: "OQtima" },
    { name: "OQtimaEU-Live", broker: "OQtimaEU" },
    { name: "OrbexGlobal-Server", broker: "OrbexGlobal" },
    { name: "OrbiTradeBerjangka-Live", broker: "OrbiTradeBerjangka" },
    { name: "OrbiTradeSC-Live", broker: "OrbiTradeSC" },
    { name: "OrokuEdgeLtd-Live", broker: "OrokuEdgeLtd" },
    { name: "OtetGroup-MT5", broker: "OtetGroup" },
    { name: "OWMarkets-Server", broker: "OWMarkets" },
    { name: "OxSecurities-Demo", broker: "OxSecurities", isDemo: true },
    { name: "OxSecurities-Live", broker: "OxSecurities" },
    { name: "OzenfxMarkets-Server", broker: "XM" },
    { name: "PanenKapital-Server", broker: "PanenKapital" },
    { name: "PellironUniversal-Server", broker: "PellironUniversal" },
    { name: "PemaxxLiquidity-Server", broker: "PemaxxLiquidity" },
    { name: "Pepperstone-Demo", broker: "Pepperstone", isDemo: true },
    { name: "Pepperstone-Live01", broker: "Pepperstone" },
    { name: "Pepperstone-Live02", broker: "Pepperstone" },
    { name: "Pepperstone-MT5-Live01", broker: "Pepperstone" },
    { name: "PepperstoneBS-MT5-Live01", broker: "Pepperstone" },
    { name: "PepperstoneEU-Live", broker: "Pepperstone" },
    { name: "PepperstoneFinancialUAE-MT5-Live01", broker: "Pepperstone" },
    { name: "PepperstoneGmbH-Live", broker: "Pepperstone" },
    { name: "PepperstoneKE-MT5-Live01", broker: "Pepperstone" },
    { name: "PepperstoneMU-MT5-Live01", broker: "Pepperstone" },
    { name: "PepperstoneUAE-MT5-Live01", broker: "Pepperstone" },
    { name: "PepperstoneUK-Demo", broker: "Pepperstone", isDemo: true },
    { name: "PepperstoneUK-Live", broker: "Pepperstone" },
    { name: "PGBerjangka2-Live", broker: "PGBerjangka2" },
    { name: "PhyntexGroupLimited-Live", broker: "PhyntexGroupLimited" },
    { name: "Pipcy-Trade", broker: "Pipcy" },
    { name: "PipstoneCapital-Server", broker: "PipstoneCapital" },
    { name: "PlexyTrade-Server01", broker: "PlexyTrade" },
    { name: "PlusMarketsTrading-MT5", broker: "PlusMarketsTrading" },
    { name: "PMEX-Demo", broker: "PMEX", isDemo: true },
    { name: "PoTrade-MT5", broker: "PoTrade" },
    { name: "PPLInternational-Main", broker: "PPLInternational" },
    { name: "Praxis-Live", broker: "Axi" },
    { name: "PreferredCapital-Server", broker: "PreferredCapital" },
    { name: "PremierEquityFutures-MT5-Live", broker: "PremierEquityFutures" },
    { name: "PrimaX-Trade", broker: "PrimaX" },
    { name: "PrimeTimeGlobalMarkets-Live", broker: "PrimeTimeGlobalMarkets" },
    { name: "PrimeWaveFx-Trade", broker: "PrimeWaveFx" },
    { name: "PrimeXCapital-Live", broker: "PrimeXCapital" },
    { name: "PrimeXM-DEV1", broker: "XM" },
    { name: "PrimusMarkets-demo", broker: "PrimusMarkets", isDemo: true },
    { name: "PrimusMarkets-Live1", broker: "PrimusMarkets" },
    { name: "ProdigitInvestments-Live", broker: "IG" },
    { name: "ProdigyTrading-Server", broker: "IG" },
    { name: "ProFinWealth-Live", broker: "ProFinWealth" },
    { name: "ProopCoFX-Live", broker: "ProopCoFX" },
    { name: "ProperFX-Live", broker: "ProperFX" },
    { name: "PropXPLtd-Server", broker: "PropXPLtd" },
    { name: "Prorex-Server", broker: "Prorex" },
    { name: "PSFXInternational-Server", broker: "PSFXInternational" },
    { name: "PTBPlutusTradebase-Triple", broker: "PTBPlutusTradebase" },
    { name: "PUPrime-Demo", broker: "PUPrime", isDemo: true },
    { name: "PUPrime-Live", broker: "PUPrime" },
    { name: "PUPrime-Live 4", broker: "PUPrime" },
    { name: "PUPrime-Live 6", broker: "PUPrime" },
    { name: "PUPrime-Live 7", broker: "PUPrime" },
    { name: "PUPrime-Live2", broker: "PUPrime" },
    { name: "PUPrimeTrading-Live", broker: "PUPrimeTrading" },
    { name: "PureMGlobal-MT5", broker: "PureMGlobal" },
    { name: "PurpleTradingSC-01MT5", broker: "PurpleTradingSC" },
    { name: "PXBTTrading-1", broker: "PXBTTrading" },
    { name: "QberxCapital-Server", broker: "QberxCapital" },
    { name: "QRSGlobal-Server", broker: "QRSGlobal" },
    { name: "QuantTekel-server", broker: "QuantTekel" },
    { name: "QubeMarketsGroup-Trade", broker: "QubeMarketsGroup" },
    { name: "RadexMarkets-Live", broker: "XM" },
    { name: "RaiseGlobal-Live", broker: "RaiseGlobal" },
    { name: "RaiseGlobalSA-LIVE", broker: "RaiseGlobalSA" },
    { name: "RaiseGroup-Server", broker: "RaiseGroup" },
    { name: "RallyTrade-Live", broker: "RallyTrade" },
    { name: "RawForex-Live", broker: "RawForex" },
    { name: "RazorMarkets-Live", broker: "RazorMarkets" },
    { name: "RCGMarkets-Demo", broker: "RCGMarkets", isDemo: true },
    { name: "RCGMarkets-Real", broker: "RCGMarkets" },
    { name: "Redmars-Server", broker: "Redmars" },
    { name: "RegulusCapital-Server", broker: "RegulusCapital" },
    { name: "RigateMarkets-Server", broker: "IG" },
    { name: "RightGroup-Live", broker: "IG" },
    { name: "RiyadexFinancial-Live", broker: "RiyadexFinancial" },
    { name: "RKXFinancial-Live", broker: "RKXFinancial" },
    { name: "RLCrates-Live", broker: "RLCrates" },
    { name: "RoboForex-Demo", broker: "RoboForex", isDemo: true },
    { name: "RoboForex-ECN", broker: "RoboForex" },
    { name: "RoboForex-Pro", broker: "RoboForex" },
    { name: "RoboMarkets-Pro", broker: "RoboMarkets" },
    { name: "RoboMarketsCY-ECN", broker: "RoboMarketsCY" },
    { name: "RoboMarketsSC-ECN", broker: "RoboMarketsSC" },
    { name: "RocketX-Live", broker: "RocketX" },
    { name: "RockWest-Server", broker: "RockWest" },
    { name: "RossiCapital-Server", broker: "RossiCapital" },
    { name: "RoxCapitals-Server", broker: "RoxCapitals" },
    { name: "RRFX-Live", broker: "RRFX" },
    { name: "RSFinance-Server", broker: "RSFinance" },
    { name: "Rubyfx-Live", broker: "Rubyfx" },
    { name: "SaracenMarkets-Live", broker: "SaracenMarkets" },
    { name: "SarmayeGozareBartar-Real", broker: "SarmayeGozareBartar" },
    { name: "ScapBroker-Server", broker: "ScapBroker" },
    { name: "SCFMLimited-Demo2", broker: "SCFMLimited", isDemo: true },
    { name: "SCFMLimited-Live2", broker: "SCFMLimited" },
    { name: "ScopeMarkets-Live", broker: "ScopeMarkets" },
    { name: "SeacrestMarkets-MT5", broker: "SeacrestMarkets" },
    { name: "Seaprimecapitals-Live", broker: "Seaprimecapitals" },
    { name: "SECMarkets-Demo", broker: "SECMarkets", isDemo: true },
    { name: "SevenCapitalsBrokerage-LIVE", broker: "SevenCapitalsBrokerage" },
    { name: "SharkFunded-Live", broker: "SharkFunded" },
    { name: "SicherMayorLtd-Server", broker: "SicherMayorLtd" },
    { name: "SightGainMarkets-Server", broker: "IG" },
    { name: "SigmaOneCapital-Server", broker: "IG" },
    { name: "SLHMarkets-Live", broker: "SLHMarkets" },
    { name: "SmartTrader-Server", broker: "SmartTrader" },
    { name: "SolicitCapital-RO1", broker: "SolicitCapital" },
    { name: "SolidECN-Server", broker: "SolidECN" },
    { name: "SpaceMarkets-Live", broker: "SpaceMarkets" },
    { name: "SpecCapitals-Main", broker: "SpecCapitals" },
    { name: "SpiceProp-Trade", broker: "SpiceProp" },
    { name: "Spredixmarkets-Server", broker: "XM" },
    { name: "SquaredFinancialSC-MT5 Demo", broker: "SquaredFinancialSC", isDemo: true },
    { name: "SquaredFinancialSC-MT5 Live", broker: "SquaredFinancialSC" },
    { name: "StarBridgeCapitalGroup-MT5-Live 2", broker: "StarBridgeCapitalGroup" },
    { name: "StarlightCapital-Server", broker: "IG" },
    { name: "STARTRADERFinancial-Demo", broker: "STARTRADER", isDemo: true },
    { name: "STARTRADERFinancial-Live", broker: "STARTRADER" },
    { name: "STARTRADERFinancial-Live 3", broker: "STARTRADER" },
    { name: "STARTRADERFinancial-Live 4", broker: "STARTRADER" },
    { name: "STARTRADERFinancial-Live 5", broker: "STARTRADER" },
    { name: "STARTRADERFinancial-Live 6", broker: "STARTRADER" },
    { name: "STARTRADERFinancial-Live2", broker: "STARTRADER" },
    { name: "STARTRADERPrimeGlobal-Live", broker: "STARTRADER" },
    { name: "starwaveFX-server", broker: "starwaveFX" },
    { name: "STBProvider-Server", broker: "STBProvider" },
    { name: "STGlobalMarketsLtd-Live-1", broker: "STGlobalMarketsLtd" },
    { name: "SthirixCapital-Server", broker: "SthirixCapital" },
    { name: "STMarket-Demo", broker: "STMarket", isDemo: true },
    { name: "STMarket-Live", broker: "STMarket" },
    { name: "StockfishFx-Server", broker: "StockfishFx" },
    { name: "StoicFX-Trade", broker: "StoicFX" },
    { name: "StonefortSecurities-Server", broker: "StonefortSecurities" },
    { name: "StoxPips-Trade", broker: "StoxPips" },
    { name: "StraitsFutures-Live", broker: "StraitsFutures" },
    { name: "StriforMU-Trade", broker: "StriforMU" },
    { name: "StrikeProfx-Server", broker: "StrikeProfx" },
    { name: "Supertrade-Server", broker: "Supertrade" },
    { name: "SureLeverageFunding-MT5", broker: "SureLeverageFunding" },
    { name: "SwiftTrader-Server", broker: "SwiftTrader" },
    { name: "SwissinvestorSA-Server", broker: "SwissinvestorSA" },
    { name: "Swissquote-Instit-Server", broker: "Swissquote" },
    { name: "Swissquote-Server", broker: "Swissquote" },
    { name: "SwissquoteBankEU-Server", broker: "Swissquote" },
    { name: "SwissquoteCapitalMarkets-Server", broker: "Swissquote" },
    { name: "SwissquoteLtd-Server", broker: "Swissquote" },
    { name: "SwitchMarkets-Live", broker: "SwitchMarkets" },
    { name: "TabTrade-Live", broker: "TabTrade" },
    { name: "TagMarkets-Server", broker: "TagMarkets" },
    { name: "TargetFX-Live", broker: "TargetFX" },
    { name: "tastyfx-LIVE", broker: "tastyfx" },
    { name: "Taurex-Demo", broker: "Taurex", isDemo: true },
    { name: "Taurex-LIVE", broker: "Taurex" },
    { name: "TaurexUK-LIVE", broker: "TaurexUK" },
    { name: "TCBridge-Demo", broker: "TCBridge", isDemo: true },
    { name: "TCBridge-Live", broker: "TCBridge" },
    { name: "TDMarkets-Primary", broker: "TDMarkets" },
    { name: "tegasFX-Main-UK", broker: "tegasFX" },
    { name: "TemplerSecuritiesJSC-Server 1", broker: "TemplerSecuritiesJSC" },
    { name: "TenTrade-Server", broker: "TenTrade" },
    { name: "TGMarkets-Server", broker: "TGMarkets" },
    { name: "Thaurus-Demo", broker: "Thaurus", isDemo: true },
    { name: "Thaurus-Server", broker: "Thaurus" },
    { name: "The5ers-Server", broker: "The5ers" },
    { name: "TheConcept-Trade", broker: "TheConcept" },
    { name: "ThePropTrade-Server", broker: "ThePropTrade" },
    { name: "ThinkMarkets-Demo", broker: "ThinkMarkets", isDemo: true },
    { name: "ThinkMarkets-Live", broker: "ThinkMarkets" },
    { name: "TibiGlobe-Live", broker: "IG" },
    { name: "Tickmill-Demo", broker: "Tickmill", isDemo: true },
    { name: "Tickmill-Live", broker: "Tickmill" },
    { name: "TickmillAsia-Live", broker: "Tickmill" },
    { name: "TickmillEU-Demo", broker: "Tickmill", isDemo: true },
    { name: "TickmillEU-Live", broker: "Tickmill" },
    { name: "TickmillUK-Demo", broker: "Tickmill", isDemo: true },
    { name: "TickmillUK-Live", broker: "Tickmill" },
    { name: "TickrsFinancialSingapore-Trade", broker: "TickrsFinancialSingapore" },
    { name: "TigerFX-Live1", broker: "IG" },
    { name: "TIOMarkets-Live1", broker: "TIOMarkets" },
    { name: "TIOMarketsUK-Live1", broker: "TIOMarketsUK" },
    { name: "TitanFX-MT5-01", broker: "TitanFX" },
    { name: "TMFinancials-Server", broker: "TMFinancials" },
    { name: "TMGM.TradeMaxAU-Demo", broker: "TMGM.TradeMaxAU", isDemo: true },
    { name: "TNFX-Live", broker: "TNFX" },
    { name: "TopFX-Live", broker: "TopFX" },
    { name: "TopOneTrader-MT5", broker: "TopOneTrader" },
    { name: "TopwealthTrading-Live", broker: "TopwealthTrading" },
    { name: "TPTradesGroup-Online", broker: "TPTradesGroup" },
    { name: "Trade245-Live", broker: "Trade245" },
    { name: "Trade245Global-Live", broker: "Trade245Global" },
    { name: "TradeifyVentures-Trade", broker: "TradeifyVentures" },
    { name: "TradeMaxGlobal-Demo", broker: "TradeMaxGlobal", isDemo: true },
    { name: "TradeMaxGlobal-Live", broker: "TradeMaxGlobal" },
    { name: "trademaxglobal-live2", broker: "trademaxglobal" },
    { name: "TradeQuo-Server", broker: "TradeQuo" },
    { name: "TradeQuoGlobal-Server", broker: "TradeQuoGlobal" },
    { name: "Traderscale-Trade", broker: "Traderscale" },
    { name: "TradersHubLtd-Live", broker: "TradersHubLtd" },
    { name: "TradersTrust-Server", broker: "TradersTrust" },
    { name: "TradersWay-Demo", broker: "TradersWay", isDemo: true },
    { name: "Tradersway-Live", broker: "Tradersway" },
    { name: "TraderWaves", broker: "TraderWaves" },
    { name: "TradeSmart-Server01", broker: "TradeSmart" },
    { name: "Tradeview-Demo", broker: "Tradeview", isDemo: true },
    { name: "Tradeview-Live", broker: "Tradeview" },
    { name: "TradewillGlobal-Server", broker: "TradewillGlobal" },
    { name: "TradexMaxima-Server", broker: "XM" },
    { name: "Tradin-Real", broker: "Tradin" },
    { name: "Trading.comAU-MT5", broker: "Trading.comAU" },
    { name: "Trading.comEU-MT5", broker: "Trading.comEU" },
    { name: "Trading.comMarkets-MT5", broker: "Trading.comMarkets" },
    { name: "Trading.comUK-MT5", broker: "Trading.comUK" },
    { name: "TradingCult-Server", broker: "TradingCult" },
    { name: "TradinGlobal-Real", broker: "TradinGlobal" },
    { name: "TradingProInternational-Demo", broker: "TradingProInternational", isDemo: true },
    { name: "TradingProInternational-Live", broker: "TradingProInternational" },
    { name: "TradingRoad-Server", broker: "TradingRoad" },
    { name: "TradingSphere-Real1", broker: "TradingSphere" },
    { name: "TradiumHouse-Server", broker: "TradiumHouse" },
    { name: "TradonaMarkets-Server", broker: "TradonaMarkets" },
    { name: "TransXMarket-Server", broker: "XM" },
    { name: "TRDX-Server", broker: "TRDX" },
    { name: "TreeStockInvestment-Server", broker: "TreeStockInvestment" },
    { name: "Triangleview-Demo", broker: "Triangleview", isDemo: true },
    { name: "TridentproFuture-Demo", broker: "TridentproFuture", isDemo: true },
    { name: "TriveEurope-Demo2", broker: "TriveEurope", isDemo: true },
    { name: "TriveEurope-Live2", broker: "TriveEurope" },
    { name: "TriveEurope-MT5Live-2", broker: "TriveEurope" },
    { name: "TriveInternational-MT5Live-1", broker: "TriveInternational" },
    { name: "TrustCapital-Server", broker: "TrustCapital" },
    { name: "TrustCapitalLtd-Server", broker: "TrustCapitalLtd" },
    { name: "TSGBrokers-LiveTrade", broker: "TSGBrokers" },
    { name: "TTPMarkets-Server", broker: "TTPMarkets" },
    { name: "TTPTrading-Server", broker: "TTPTrading" },
    { name: "TTTMarkets-Ltd", broker: "TTTMarkets" },
    { name: "TX3FundingGlobal-Server", broker: "TX3FundingGlobal" },
    { name: "TX3MarketsGlobal-Live", broker: "TX3MarketsGlobal" },
    { name: "UEXOGlobal-Trade", broker: "UEXOGlobal" },
    { name: "UltimaMarkets-Demo", broker: "UltimaMarkets", isDemo: true },
    { name: "UltimaMarkets-Live 1", broker: "UltimaMarkets" },
    { name: "UltimaMarkets-Live 2", broker: "UltimaMarkets" },
    { name: "UltimaMarketsUK-Live", broker: "UltimaMarketsUK" },
    { name: "UNFXB-Real", broker: "UNFXB" },
    { name: "UniglobeMarkets-Live", broker: "IG" },
    { name: "Upcomers-Server", broker: "Upcomers" },
    { name: "ValetaxGlobal-Live3", broker: "ValetaxGlobal" },
    { name: "ValetaxIntl-Live2", broker: "Axi" },
    { name: "ValetaxIntl-Live5", broker: "Axi" },
    { name: "ValetaxIntl-Live7", broker: "Axi" },
    { name: "ValorMarkets-Server", broker: "ValorMarkets" },
    { name: "Valutrades-Demo", broker: "Valutrades", isDemo: true },
    { name: "ValutradesSeychelles-Demo", broker: "ValutradesSeychelles", isDemo: true },
    { name: "VantageFX-Demo", broker: "Vantage", isDemo: true },
    { name: "VantageFX-Live", broker: "Vantage" },
    { name: "VantageFX-Live 3", broker: "Vantage" },
    { name: "VantageFX-Live 4", broker: "Vantage" },
    { name: "VantageFX-Live 5", broker: "Vantage" },
    { name: "VantageFX-Live 6", broker: "Vantage" },
    { name: "VantageFX-Live 8", broker: "Vantage" },
    { name: "VantageGlobalPrimeAU-Live", broker: "Vantage" },
    { name: "VantageGlobalPrimeLLP-Demo", broker: "Vantage", isDemo: true },
    { name: "VantageGlobalPrimeLLP-Live", broker: "Vantage" },
    { name: "VantageInternational-Demo", broker: "Vantage", isDemo: true },
    { name: "VantageInternational-Live", broker: "Vantage" },
    { name: "Vantageinternational-Live 10", broker: "Vantage" },
    { name: "VantageInternational-Live 11", broker: "Vantage" },
    { name: "VantageInternational-Live 13", broker: "Vantage" },
    { name: "VantageInternational-Live 14", broker: "Vantage" },
    { name: "VantageInternational-Live 15", broker: "Vantage" },
    { name: "VantageInternational-Live 19", broker: "Vantage" },
    { name: "Vantageinternational-Live 21", broker: "Vantage" },
    { name: "VantageInternational-Live 3", broker: "Vantage" },
    { name: "VantageInternational-Live 4", broker: "Vantage" },
    { name: "VantageInternational-Live 5", broker: "Vantage" },
    { name: "VantageInternational-Live 6", broker: "Vantage" },
    { name: "vantageinternational-live 7", broker: "Vantage" },
    { name: "VantageInternational-Live 8", broker: "Vantage" },
    { name: "VantageMarkets-Demo", broker: "Vantage", isDemo: true },
    { name: "VantageMarkets-Live", broker: "Vantage" },
    { name: "VantageMarkets-Live 1", broker: "Vantage" },
    { name: "VantageMarkets-Live 10", broker: "Vantage" },
    { name: "VantageMarkets-Live 11", broker: "Vantage" },
    { name: "VantageMarkets-Live 13", broker: "Vantage" },
    { name: "VantageMarkets-Live 14", broker: "Vantage" },
    { name: "VantageMarkets-Live 15", broker: "Vantage" },
    { name: "VantageMarkets-Live 19", broker: "Vantage" },
    { name: "VantageMarkets-Live 2", broker: "Vantage" },
    { name: "VantageMarkets-Live 21", broker: "Vantage" },
    { name: "VantageMarkets-Live 3", broker: "Vantage" },
    { name: "Vantagemarkets-live 4", broker: "Vantage" },
    { name: "VantageMarkets-Live 4", broker: "Vantage" },
    { name: "VantageMarkets-Live 5", broker: "Vantage" },
    { name: "vantagemarkets-live 6", broker: "Vantage" },
    { name: "VantageMarkets-Live 7", broker: "Vantage" },
    { name: "VantageMarkets-Live 8", broker: "Vantage" },
    { name: "VantageMarketsMU-Demo", broker: "Vantage", isDemo: true },
    { name: "VantagePrimeLimited-Demo", broker: "Vantage", isDemo: true },
    { name: "VantagePrimeLimited-Live", broker: "Vantage" },
    { name: "VantageTradingLtd-Live", broker: "Vantage" },
    { name: "Vanto-Trade", broker: "Vanto" },
    { name: "VantosMarketsUK-Demo", broker: "VantosMarketsUK", isDemo: true },
    { name: "VanVest-MT5Trial9", broker: "VanVest", isDemo: true },
    { name: "VaultMarkets-Live", broker: "VaultMarkets" },
    { name: "VCGMarkets-Server", broker: "VCGMarkets" },
    { name: "Vebson-Server", broker: "Vebson" },
    { name: "VelocityTrade-Trade", broker: "VelocityTrade" },
    { name: "VersusTrade-Live1", broker: "VersusTrade" },
    { name: "Vestrado-Server", broker: "Vestrado" },
    { name: "VexPro-Server", broker: "VexPro" },
    { name: "VIGGroupFutures-Real", broker: "IG" },
    { name: "VirtualMarkets-Demo", broker: "VirtualMarkets", isDemo: true },
    { name: "VistovaMarkets-Server", broker: "VistovaMarkets" },
    { name: "Vittaverse-Server", broker: "Vittaverse" },
    { name: "VolarixMarkets-Server", broker: "XM" },
    { name: "volnexcapital-trade", broker: "volnexcapital" },
    { name: "VortexFX-Servers", broker: "VortexFX" },
    { name: "VSMarkets-Server", broker: "VSMarkets" },
    { name: "VTMarkets-Demo", broker: "VTMarkets", isDemo: true },
    { name: "VTMarkets-Live", broker: "VTMarkets" },
    { name: "VTMarkets-Live 2", broker: "VTMarkets" },
    { name: "VTMarkets-Live 3", broker: "VTMarkets" },
    { name: "VTmarkets-Live 5", broker: "VTmarkets" },
    { name: "Vtmarkets-Live 6", broker: "Vtmarkets" },
    { name: "VTMarkets-Live 7", broker: "VTMarkets" },
    { name: "VTMarkets-Live 8", broker: "VTMarkets" },
    { name: "VTMarkets-Live 9", broker: "VTMarkets" },
    { name: "VTMarketsLtd-Live 4", broker: "VTMarketsLtd" },
    { name: "WefundMarkets-Live", broker: "WefundMarkets" },
    { name: "WeGetFunded-Server", broker: "WeGetFunded" },
    { name: "WeGolden-Live", broker: "WeGolden" },
    { name: "Weltrade-Demo", broker: "Weltrade", isDemo: true },
    { name: "Weltrade-Real", broker: "Weltrade" },
    { name: "WeltradeGlobal-Real", broker: "WeltradeGlobal" },
    { name: "WeMasterTrade-Virtual", broker: "WeMasterTrade" },
    { name: "WesternSahara-server", broker: "WesternSahara" },
    { name: "WeTrade-MT5", broker: "WeTrade" },
    { name: "WeTradeCapital-Trade", broker: "WeTradeCapital" },
    { name: "WeTradeInternational-Trade", broker: "WeTradeInternational" },
    { name: "WeTradeMarket-Live", broker: "WeTradeMarket" },
    { name: "whiteforex-Server", broker: "whiteforex" },
    { name: "windsorBrokers1-Demo", broker: "windsorBrokers1", isDemo: true },
    { name: "WindsorBrokers1-REAL1", broker: "WindsorBrokers1" },
    { name: "WINDSORBROKERS2-DEMO", broker: "WINDSORBROKERS2", isDemo: true },
    { name: "WindsorBrokers2-REAL1", broker: "WindsorBrokers2" },
    { name: "WindsorBrokers3-Real1", broker: "WindsorBrokers3" },
    { name: "WingoGroupLtd-Server", broker: "WingoGroupLtd" },
    { name: "Winprofx-Live", broker: "Winprofx" },
    { name: "WinstonePrime-MT5", broker: "WinstonePrime" },
    { name: "WisdomFinancial-Server", broker: "WisdomFinancial" },
    { name: "Wisuno-MT5", broker: "Wisuno" },
    { name: "WMMarkets-Demo", broker: "WMMarkets", isDemo: true },
    { name: "Wonderinterest-Live", broker: "Wonderinterest" },
    { name: "WorldFinanceEnterprise-Server", broker: "WorldFinanceEnterprise" },
    { name: "WRDNB-Live", broker: "WRDNB" },
    { name: "WSFmarkets-Server", broker: "WSFmarkets" },
    { name: "WSFunded-Server", broker: "WSFunded" },
    { name: "xChief-MT5", broker: "xChief" },
    { name: "XelansMarkets-ECN", broker: "XelansMarkets" },
    { name: "Xellion-live", broker: "Xellion" },
    { name: "XenonGroup-Trade", broker: "XenonGroup" },
    { name: "xetacapital-server", broker: "xetacapital" },
    { name: "XFunded-Trade", broker: "XFunded" },
    { name: "XinWangGoldenCompany-Live", broker: "XinWangGoldenCompany" },
    { name: "Xlence-Demo1", broker: "Xlence", isDemo: true },
    { name: "xlence-real1", broker: "xlence" },
    { name: "XM.COM-MT5", broker: "XM" },
    { name: "XmaxMarkets-Live", broker: "XM" },
    { name: "XMGlobal-Demo", broker: "XM", isDemo: true },
    { name: "XMGlobal-MT5", broker: "XM" },
    { name: "XMGlobal-MT5 10", broker: "XM" },
    { name: "XMGlobal-MT5 11", broker: "XM" },
    { name: "XMGlobal-MT5 12", broker: "XM" },
    { name: "XMGlobal-MT5 13", broker: "XM" },
    { name: "XMGlobal-MT5 14", broker: "XM" },
    { name: "XMGlobal-MT5 15", broker: "XM" },
    { name: "XMGlobal-MT5 16", broker: "XM" },
    { name: "XMGlobal-MT5 17", broker: "XM" },
    { name: "XMGlobal-MT5 18", broker: "XM" },
    { name: "XMGlobal-MT5 19", broker: "XM" },
    { name: "XMGlobal-MT5 2", broker: "XM" },
    { name: "XMGlobal-MT5 20", broker: "XM" },
    { name: "XMGlobal-MT5 3", broker: "XM" },
    { name: "XMGlobal-MT5 4", broker: "XM" },
    { name: "XMGlobal-MT5 5", broker: "XM" },
    { name: "XMGlobal-MT5 6", broker: "XM" },
    { name: "XMGlobal-MT5 7", broker: "XM" },
    { name: "XMGlobal-MT5 8", broker: "XM" },
    { name: "XMGlobal-MT5 9", broker: "XM" },
    { name: "XMGlobalBVI-MT5 4", broker: "XM" },
    { name: "XMGlobalKE-MT5 16", broker: "XM" },
    { name: "XMGlobalKE-MT5 2", broker: "XM" },
    { name: "XMGlobalMU-MT5 11", broker: "XM" },
    { name: "XMGlobalMU-MT5 14", broker: "XM" },
    { name: "XMGlobalMU-MT5 2", broker: "XM" },
    { name: "XMGlobalMU-MT5 4", broker: "XM" },
    { name: "XMGlobalMU-MT5 5", broker: "XM" },
    { name: "XMGlobalMU-MT5 6", broker: "XM" },
    { name: "XMGlobalMU-MT5 8", broker: "XM" },
    { name: "XMGlobalSC-MT5 6", broker: "XM" },
    { name: "XMMena-MT5", broker: "XM" },
    { name: "XMTrading-MT5 2", broker: "XM" },
    { name: "XMTrading-MT5 3", broker: "XM" },
    { name: "XMTradingMU-MT5 2", broker: "XM" },
    { name: "XMZA-MT5 15", broker: "XM" },
    { name: "XPMT5-DEMO", broker: "XPMT5", isDemo: true },
    { name: "XSFintech-Demo", broker: "XSFintech", isDemo: true },
    { name: "XSFintech-REAL-1", broker: "XSFintech" },
    { name: "XSFintech-REAL-2", broker: "XSFintech" },
    { name: "XSFintech-REAL-3", broker: "XSFintech" },
    { name: "XSMarkets-REAL-1", broker: "XSMarkets" },
    { name: "XtreamMarkets-Server", broker: "XtreamMarkets" },
    { name: "XyloMarkets-Server", broker: "XyloMarkets" },
    { name: "YaGroup-Server", broker: "YaGroup" },
    { name: "YAITradingCoLtd-Real", broker: "YAITradingCoLtd" },
    { name: "YCMInvest-Server", broker: "YCMInvest" },
    { name: "YLDFX-Server 01", broker: "YLDFX" },
    { name: "YWO-Trade", broker: "YWO" },
    { name: "ZealCapitalMarketSC-Demo", broker: "ZealCapitalMarketSC", isDemo: true },
    { name: "Zenexofx-Trade", broker: "Zenexofx" },
    { name: "ZenoraCapital-Server", broker: "ZenoraCapital" },
    { name: "ZeroMarkets-1", broker: "Zero Markets" },
    { name: "ZeroMarketsAU-Demo MT5", broker: "Zero Markets", isDemo: true },
    { name: "ZForexcapitalmarket-Server", broker: "ZForexcapitalmarket" },
    { name: "ZiraatFX-Real", broker: "ZiraatFX" },
    { name: "Zonofx-Server", broker: "Zonofx" },
    { name: "ZoraCapital-Server", broker: "ZoraCapital" },
    { name: "ZuperiorFX-Server", broker: "ZuperiorFX" },
    { name: "STARTRADERFinancial-Live", broker: "StarTrader" },
    { name: "STARTRADERFinancial-Live 2", broker: "StarTrader" },
    { name: "STARTRADERFinancial-Live 3", broker: "StarTrader" },
    { name: "STARTRADERFinancial-Demo", broker: "StarTrader", isDemo: true },
    { name: "STARTRADERInternational-Live", broker: "StarTrader" },
    { name: "STARTRADERInternational-Demo", broker: "StarTrader", isDemo: true },
];

/**
 * Filter servers by search query (matches server name or broker name).
 */
export function filterMt5Servers(query: string, limit = 50): MT5ServerItem[] {
    const q = query.trim().toLowerCase();
    if (!q) {
        return POPULAR_MT5_SERVERS.slice(0, limit);
    }
    const filtered = POPULAR_MT5_SERVERS.filter(
        (s) =>
            s.name.toLowerCase().includes(q) ||
            (s.broker && s.broker.toLowerCase().includes(q))
    );
    return filtered.slice(0, limit);
}

/**
 * Get server list filtered by broker code or name (e.g. EXNESS, VANTAGE, VTMARKETS, ULTIMAMARKETS).
 * If no broker is provided or unknown, returns all POPULAR_MT5_SERVERS.
 */
export function getServersForBroker(broker?: string | null): MT5ServerItem[] {
    if (!broker || !broker.trim()) {
        return POPULAR_MT5_SERVERS;
    }

    const b = broker.trim().toLowerCase();

    // Map known broker codes or names to keywords
    const keywords: string[] = [];
    if (b === "exness" || b.includes("exness")) {
        keywords.push("exness");
    } else if (b === "vantage" || b.includes("vantage")) {
        keywords.push("vantage");
    } else if (b === "vtmarkets" || b.includes("vtmarket") || b.includes("vt market")) {
        keywords.push("vtmarket", "vt market");
    } else if (b === "ultimamarkets" || b.includes("ultima")) {
        keywords.push("ultima");
    } else if (b === "startrader" || b.includes("startrader") || b.includes("star trader")) {
        keywords.push("startrader", "star trader");
    } else {
        keywords.push(b);
    }

    const matched = POPULAR_MT5_SERVERS.filter((s) => {
        const sName = s.name.toLowerCase();
        const sBroker = (s.broker || "").toLowerCase();
        return keywords.some((k) => sName.includes(k) || sBroker.includes(k));
    });

    return matched.length > 0 ? matched : POPULAR_MT5_SERVERS;
}
