export const MIN_OBSERVATION_TRADES = 3;
export const MIN_ACTIONABLE_TRADES = 20;
export const MIN_SEGMENT_TRADES = 5;
export const HIGH_CONFIDENCE_TRADES = 50;

export type InsightType =
    | "RULE_VIOLATION_RECURRING"
    | "REVENGE_SIZING_PATTERN"
    | "WEAK_SESSION_DAY_SYMBOL"
    | "POSITIVE_DISCIPLINE_PATTERN"
    | "MISSING_JOURNAL_CONTEXT"
    | "MOST_TRADED_DESCRIPTIVE";
