export const tradingQuotes = [
  { text: "The goal of a successful trader is to make the best trades. Money is secondary.", author: "Alexander Elder" },
  { text: "Plan your trade and trade your plan.", author: "Jesse Livermore" },
  { text: "Cut your losses short and let your winners run.", author: "Wall Street Proverb" },
  { text: "Never let a winner turn into a loser.", author: "Trading Axiom" },
  { text: "In trading, the impossible happens about twice a year.", author: "Henri Fayol" },
  { text: "Do more of what works and less of what doesn't.", author: "Steve Clark" },
  { text: "Don't worry about what the markets are going to do, worry about what you are going to do.", author: "Michael Carr" },
  { text: "The hard part is not predicting the market; it's controlling your own behavior.", author: "Benjamin Graham" },
  { text: "Markets can remain irrational longer than you can remain solvent.", author: "John Maynard Keynes" },
  { text: "Risk comes from not knowing what you're doing.", author: "Warren Buffett" },
  { text: "A peak performance trader is totally committed to being the best.", author: "Van K. Tharp" },
  { text: "I always define my risk, and I don't have to worry about it.", author: "Tony Saliba" },
  { text: "Losers average losers.", author: "Paul Tudor Jones" },
  { text: "There is a time to go long, a time to go short and a time to go fishing.", author: "Jesse Livermore" },
  { text: "Opportunities come infrequently. When it rains gold, put out the bucket.", author: "Warren Buffett" },
  { text: "Focus, patience, wise discernment, non-attachment: the skills you acquire in meditation are exactly the skills you need in trading.", author: "Yvan Byeajee" },
  { text: "The core secret of success is to have a robust method and the discipline to stick with it.", author: "Mark Douglas" },
  { text: "Limit your size in any position so that fear does not become the prevailing instinct guiding your judgment.", author: "Joe Vidich" },
  { text: "Success in trading comes from a clear methodology, strong risk management, and the discipline to execute them consistently.", author: "Trading Principles" },
  { text: "Every setup you take needs to have an edge.", author: "Trading Principles" },
  { text: "Emotions are your worst enemy in the stock market.", author: "Don Hayes" },
  { text: "If you cannot control your emotions, you cannot control your money.", author: "Warren Buffett" },
  { text: "Learn to take losses. The most important thing in making money is not letting your losses get out of hand.", author: "Marty Schwartz" },
  { text: "Amateurs think about how much money they can make. Professionals think about how much money they could lose.", author: "Jack Schwager" },
  { text: "Trading is 80% psychology and 20% methodology.", author: "Mark Douglas" },
  { text: "The market does not know if you are long or short and could not care less.", author: "Marty Schwartz" },
  { text: "Your biggest enemy is yourself, not the market.", author: "Trading Axiom" },
  { text: "Patience is the core of smart trading.", author: "Trading Principles" },
  { text: "Don't trade the money, trade the setups.", author: "Trading Principles" },
  { text: "Consistency is the hallmark of a successful trader.", author: "Trading Principles" },
  { text: "It's not whether you're right or wrong that's important, but how much money you make when you're right and how much you lose when you're wrong.", author: "George Soros" },
  { text: "He who knows when he can fight and when he cannot, will be victorious.", author: "Sun Tzu" },
  { text: "Sometimes the best trade is no trade.", author: "Trading Axiom" },
  { text: "The most important organ in trading is not the brain, it's the stomach.", author: "Peter Lynch" },
  { text: "Trade what's happening... not what you think is going to happen.", author: "Doug Gregory" },
  { text: "Doubt is an uncomfortable condition, but certainty is a ridiculous one.", author: "Voltaire" },
  { text: "Do not anticipate and move without market confirmation - being a little late in your trade is your insurance that you are right or wrong.", author: "Jesse Livermore" },
  { text: "Confidence is not 'I will profit on this trade.' Confidence is 'I will be fine if I don't profit from this trade.'", author: "Yvan Byeajee" },
  { text: "Successful traders are masters of their own emotions.", author: "Trading Principles" },
  { text: "A loss never bothers me after I take it. I forget it overnight.", author: "Paul Tudor Jones" },
  { text: "Do not fight the market. The trend is your friend.", author: "Trading Axiom" },
  { text: "Trading is a game of probabilities. Stop looking for certainty.", author: "Mark Douglas" },
  { text: "A successful trader is a realistic person. He knows his abilities and his limitations.", author: "Alexander Elder" },
  { text: "Losses are the tuition you pay for learning to trade.", author: "Trading Axiom" },
  { text: "A setup is merely a map. The trader is the one who chooses to follow the path.", author: "Trading Principles" },
  { text: "The longer you survive in trading, the better your chances of making real money.", author: "Trading Axiom" },
  { text: "Never add to a losing position. Just don't do it.", author: "Paul Tudor Jones" },
  { text: "Revenge trading is the fast track to a blown account.", author: "Trading Principles" },
  { text: "Keep your charts clean, your rules strict, and your mind focused.", author: "Trading Principles" }
];
