export const tradingQuotes = [
  "The goal of a successful trader is to make the best trades. Money is secondary.",
  "Plan your trade and trade your plan.",
  "Cut your losses short and let your winners run.",
  "Never let a winner turn into a loser.",
  "In trading, the impossible happens about twice a year.",
  "Do more of what works and less of what doesn't.",
  "Don't worry about what the markets are going to do, worry about what you are going to do.",
  "The hard part is not predicting the market; it's controlling your own behavior.",
  "Markets can remain irrational longer than you can remain solvent.",
  "Risk comes from not knowing what you're doing.",
  "A peak performance trader is totally committed to being the best.",
  "I always define my risk, and I don't have to worry about it.",
  "Losers average losers.",
  "There is a time to go long, a time to go short and a time to go fishing.",
  "Opportunities come infrequently. When it rains gold, put out the bucket.",
  "Focus, patience, wise discernment, non-attachment: the skills you acquire in meditation are exactly the skills you need in trading.",
  "The core secret of success is to have a robust method and the discipline to stick with it.",
  "Limit your size in any position so that fear does not become the prevailing instinct guiding your judgment.",
  "Success in trading comes from a clear methodology, strong risk management, and the discipline to execute them consistently.",
  "Every setup you take needs to have an edge.",
  "Emotions are your worst enemy in the stock market.",
  "If you cannot control your emotions, you cannot control your money.",
  "Learn to take losses. The most important thing in making money is not letting your losses get out of hand.",
  "Amateurs think about how much money they can make. Professionals think about how much money they could lose.",
  "Trading is 80% psychology and 20% methodology.",
  "A good trader has to have three things: a glass ball, a crystal ball, and a set of steel balls.",
  "The market does not know if you are long or short and could not care less.",
  "Your biggest enemy is yourself, not the market.",
  "Patience is the core of smart trading.",
  "Don't trade the money, trade the setups.",
  "Consistency is the hallmark of a successful trader.",
  "It's not whether you're right or wrong that's important, but how much money you make when you're right and how much you lose when you're wrong.",
  "He who knows when he can fight and when he cannot, will be victorious.",
  "Sometimes the best trade is no trade.",
  "The most important organ in trading is not the brain, it's the stomach.",
  "Trade what's happening... not what you think is going to happen.",
  "Doubt is an uncomfortable condition, but certainty is a ridiculous one.",
  "Do not anticipate and move without market confirmation - being a little late in your trade is your insurance that you are right or wrong.",
  "Confidence is not 'I will profit on this trade.' Confidence is 'I will be fine if I don't profit from this trade.'",
  "Successful traders are masters of their own emotions.",
  "A loss never bothers me after I take it. I forget it overnight.",
  "Do not fight the market. The trend is your friend.",
  "Trading is a game of probabilities. Stop looking for certainty.",
  "A successful trader is a realistic person. He knows his abilities and his limitations.",
  "Losses are the tuition you pay for learning to trade.",
  "A setup is merely a map. The trader is the one who chooses to follow the path.",
  "The longer you survive in trading, the better your chances of making real money.",
  "Never add to a losing position. Just don't do it.",
  "Revenge trading is the fast track to a blown account.",
  "Keep your charts clean, your rules strict, and your mind focused."
];
