
export const ErrorCode = {
    // Account Errors
    ACCOUNT_ALREADY_REGISTERED: "ACCOUNT_ALREADY_REGISTERED",
    ACCOUNT_BELONGS_TO_OTHER: "ACCOUNT_BELONGS_TO_OTHER",
    ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
    ACCOUNT_ALREADY_APPROVED: "ACCOUNT_ALREADY_APPROVED",
    ACCOUNT_ALREADY_REJECTED: "ACCOUNT_ALREADY_REJECTED",

    // Permission Errors
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_ADMIN: "NOT_ADMIN",

    // Download Errors
    NO_APPROVED_ACCOUNT: "NO_APPROVED_ACCOUNT",
    ALL_ACCOUNTS_EXPIRED: "ALL_ACCOUNTS_EXPIRED",
    PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
    FILE_NOT_AVAILABLE: "FILE_NOT_AVAILABLE",

    // Validation Errors
    INVALID_ACCOUNT_NUMBER: "INVALID_ACCOUNT_NUMBER",
    INVALID_BROKER: "INVALID_BROKER",
    REASON_REQUIRED: "REASON_REQUIRED",
    ID_REQUIRED: "ID_REQUIRED",

    // General Errors
    INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];
